project_id = "bfxahrrvoqxcdmfsvnrk"

[functions.consultar-processo]
verify_jwt = false

[functions.buscar-djen]
verify_jwt = false

[functions.monitorar-djen]
verify_jwt = false

[functions.monitorar-redistribuicoes]
verify_jwt = false

[functions.monitorar-andamentos]
verify_jwt = false

[functions.atualizar-cron-monitoramento]
verify_jwt = true

[functions.cadastrar-equipe]
verify_jwt = true

[functions.atualizar-usuario]
verify_jwt = true

[functions.monitorar-distribuicoes]
verify_jwt = false