// Versão do sistema - atualizar a cada release
export const APP_VERSION = "6.0.0";

// Changelog resumido (opcional, para referência interna)
export const VERSION_HISTORY = [
  { version: "1.0.0", date: "2026-01-30", notes: "Versão inicial com versionamento" },
  { version: "1.0.1", date: "2026-01-30", notes: "Correções no dashboard DJEN (destravamento/execução)" },
  { version: "1.0.2", date: "2026-01-31", notes: "Correção validação OAB+nome para advogados DJEN" },
  { version: "1.0.3", date: "2026-01-31", notes: "Reversão para modelo sequencial simples - progresso funcional" },
  { version: "1.0.4", date: "2026-01-31", notes: "Sistema de checkpoint e retomada de execução" },
  { version: "1.0.5", date: "2026-01-31", notes: "Otimização de performance - delays reduzidos, loop simplificado" },
  { version: "1.0.6", date: "2026-01-31", notes: "Contagem DJEN deduplicada - consistência Card x Análise" },
  { version: "1.0.7", date: "2026-05-01", notes: "Sincronização Dra. Janaina Completa como fonte de verdade" },
  { version: "1.0.8", date: "2026-05-04", notes: "Comentários de coordenação em publicações DJEN (UI + relatórios PDF/DOC)" },
  { version: "2.0", date: "2026-05-29", notes: "Marco 2.0: auto-save por aba, controles de acesso refinados em Distribuição TST" },
  { version: "2.1", date: "2026-06-12", notes: "Tags de status (Problema Judit, Segredo, Recurso de terceiro, CEJUSC) na lista de Distribuição TST" },
  { version: "2.2", date: "2026-06-12", notes: "Cards de stats unificados em Distribuição TST (Benner, Judit, Equipe, Dossiês)" },
  { version: "4.3.0", date: "2026-07-28", notes: "Correção das permissões de comentários em prazos/tarefas e audiências" },
  { version: "4.3.1", date: "2026-07-28", notes: "Painel da Equipe compacto e melhorias na visão de itens por membro" },
  { version: "4.3.2", date: "2026-07-29", notes: "Contador de mensagens não lidas ao lado da versão e no botão Alertas" },
  { version: "4.3.3", date: "2026-07-31", notes: "Etiquetas por coordenação em Clientes, Processos, Itens e Publicações" },
  { version: "4.3.4", date: "2026-08-03", notes: "Auditoria da Distribuição TST e normalização de Recorrente (Terceiro → Outra) na Carga Benner" },
  { version: "4.3.5", date: "2026-08-04", notes: "Cards compactos no Painel de Controle, correção do salvamento de audiências e alertas de prazos perdidos ignorando itens encerrados" },
  { version: "4.3.6", date: "2026-08-04", notes: "Lista lateral de atividades do dia no calendário do Painel de Controle (estilo Astrea)" },
  { version: "4.3.7", date: "2026-08-04", notes: "Exportação por período/tipos, filtros com botão Filtrar e digitação livre de datas" },
  { version: "4.3.8", date: "2026-08-05", notes: "Alerta por e-mail quando uma execução do DJEN Termos encontra mais publicações que a execução anterior do dia (BRT)" },
  { version: "4.3.9", date: "2026-08-06", notes: "Indicadores: filtros por coordenação, usuário e período (últimos 12 meses, ano específico ou todos os anos)" },
  { version: "4.4.0", date: "2026-08-06", notes: "Distribuição TST: seleção por quantidade (1 até o total filtrado) na lista" },
  { version: "4.4.1", date: "2026-08-07", notes: "Análise DJEN: Salvar e ler marca o grupo corretamente, data base da publicação e coordenador fixo como envolvido" },
  { version: "4.4.2", date: "2026-08-09", notes: "Acompanhamento Especial: sincronização automática Judit (partes, andamentos, análise) e card de divergências no painel" },
  { version: "4.4.3", date: "2026-08-10", notes: "Distribuição TST: relatórios e carga Benner sempre por data de distribuição (crescente), ordenação da lista salva no perfil e cabeçalho 'Data Distribuição'" },
  { version: "4.4.4", date: "2026-08-12", notes: "Atualização de versão" },
  { version: "4.4.5", date: "2026-08-12", notes: "Pessoas fixas por tipo de tarefa: janela mais larga (papéis Responsável/Envolvido sem corte)" },
  { version: "4.4.6", date: "2026-08-12", notes: "Reagendamento: nova data opcional para prazos e audiências (mantém data atual se não informada)" },
  { version: "4.4.7", date: "2026-08-12", notes: "Correção do filtro de data na tela Compara DOCs TST" },
  { version: "4.4.8", date: "2026-08-12", notes: "Relatório de auditoria da coordenação em PDF, horários das exportações Excel em BRT e conclusão apenas como situação (sem botão Concluir)" },
  { version: "4.4.9", date: "2026-08-12", notes: "Divergências Judit × formulário: botão 'Marcar todas como Ciente'; Acompanhamento Especial passa a buscar movimentações via crawler quando o cache vem sem andamentos" },
  { version: "4.5.0", date: "2026-08-12", notes: "Ajustes na Carga Benner: 'Problema Judit' não rejeita mais e coluna 'Risco' respeita a flag de mídia negativa" },
  { version: "4.5.1", date: "2026-08-14", notes: "Workflow: correção das validações de etapas (tipos, prazos e situações) e badge do menu Monitoramento contando apenas movimentações não lidas" },
  { version: "4.5.2", date: "2026-08-14", notes: "Judit deixa de chutar tipo de recurso: só preenche quando há instância recursal (TST) e nunca atribui o recurso ao banco sem evidência" },
  { version: "4.5.3", date: "2026-08-14", notes: "Ajustes de versão e menu" },
  { version: "4.5.4", date: "2026-08-16", notes: "Análise DJEN: exportações 'sem repetição' passam a unificar a mesma comunicação (processo + data + ID do documento + teor), ignorando ordem de advogados e bloco 'Intimado(s) / Citado(s)'" },
  { version: "4.5.5", date: "2026-08-18", notes: "Pool DJEN Servidor: VPS 4 e 5 reativadas via systemd (13 pistas ativas) e base para controle de retries por rodada" },
  { version: "5.0.0", date: "2026-08-18", notes: "Marco 5.0.0: publicação da versão revertida" },
  { version: "5.0.1", date: "2026-08-19", notes: "Atualização de versão" },
  { version: "5.0.2", date: "2026-08-20", notes: "Atualização de versão" },
  { version: "5.0.4", date: "2026-08-25", notes: "Atualização de versão" },
  { version: "5.0.5", date: "2026-08-26", notes: "Limpeza de duplicidades (coordenação Dra. Janaina), trava contra duplo submit em prazos, Carga Benner sem espaço após vírgula e relatório de duplicados" },
  { version: "5.0.6", date: "2026-08-28", notes: "Atualização de versão" },
  { version: "5.0.7", date: "2026-08-28", notes: "Atualização de versão" },
  { version: "5.0.8", date: "2026-08-28", notes: "Atualização de versão" },
  { version: "5.0.9", date: "2026-08-31", notes: "Análise DJEN: 'Lida (só esta)' marca estritamente a publicação clicada, sem expansão por dedup" },
  { version: "5.1.0", date: "2026-08-31", notes: "Distribuição TST: totalizadores 'A fazer' e 'Concluídos (prontos/planilhados)' alinhados aos status de conclusão" },
  { version: "5.1.1", date: "2026-08-31", notes: "Atualização de versão" },
  { version: "5.1.2", date: "2026-09-01", notes: "Outra Matéria neutra, conclusão preservada e datas no cabeçalho DJEN" },
  { version: "5.2.0", date: "2026-09-01", notes: "Painel de Controle: visões, tipos e busca por processo abaixo dos totalizadores; Exportar, Pessoas em lote e Adicionar na linha das coordenações" },
  { version: "5.3.0", date: "2026-09-01", notes: "Distribuição TST: cards por responsável com total/prontos/sem pendência/com pendências/faltam, clique nos números para filtrar; remoção de frase descritiva" },
  { version: "5.4.0", date: "2026-09-02", notes: "Distribuição TST: chance de êxito restrita a SIM/NÃO (matérias, terceiro e geral); descarte de publicações avisa sobre audiências/tarefas vinculadas e preserva vínculo" },
  { version: "5.5.0", date: "2026-09-02", notes: "Relatório de usuários cadastrados em PDF e ajustes no Painel de Controle" },
  { version: "5.5.1", date: "2026-09-03", notes: "Otimização de performance da Distribuição TST (cache compartilhado) e regra de pendências de matérias por dossiê" },
  { version: "5.5.5", date: "2026-09-03", notes: "Drawer sobreposto para tarefas nos modos Lista/Kanban/Equipe, correção de cancelamento de audiência e filtro de tipos no calendário" },
];
