
UPDATE public.coordenacoes
SET nome = 'Coordenação Dra. Renata com termos do João'
WHERE id = 'b0f690ad-68da-43d7-af5f-9adafeab3fd5';

WITH coord AS (
  SELECT 'b0f690ad-68da-43d7-af5f-9adafeab3fd5'::uuid AS cid,
         '1dd5f8e3-20fa-4e70-943c-bbbefdc9db37'::uuid AS uid
)
INSERT INTO public.monitoramentos_djen (tipo, termo_busca, termos_or, ativo, criado_por, coordenacao_id, buscar_parte)
SELECT t.tipo, t.termo, t.termos_or, true, coord.uid, coord.cid,
       CASE WHEN t.tipo = 'parte' THEN true ELSE false END
FROM coord, (VALUES
  ('palavra-chave','SANTANDER',NULL::text[]),
  ('palavra-chave','AYMORÉ',NULL),
  ('palavra-chave','SUDAMERIS',NULL),
  ('parte','Aquanima',NULL),
  ('parte','Auttar HUT',NULL),
  ('parte','Aymore',ARRAY['Aymoré']),
  ('parte','Associação Rede Iberoamericana de Universidades de Pesquisa',NULL),
  ('parte','Atual Companhia Securitizadora',NULL),
  ('parte','BANCO ABN',NULL),
  ('parte','BANCO HYUNDAI',NULL),
  ('parte','BANCO REAL',NULL),
  ('parte','Banesprev',NULL),
  ('parte','Banco Bandepe',NULL),
  ('parte','Banco Bonsucesso',NULL),
  ('parte','Banco BS2',NULL),
  ('parte','Banco RCI',NULL),
  ('parte','BEN BENEFÍCIOS',NULL),
  ('parte','Bonsucesso Tecnologia',NULL),
  ('parte','BPV - Promotora de Vendas e Cobranças',NULL),
  ('parte','BW Guirapa',ARRAY['Guirapá']),
  ('parte','CIBRASEC',NULL),
  ('parte','Crediperto',NULL),
  ('parte','ESFERA FIDELIDADE',NULL),
  ('parte','Estruturadora Brasileira de Projetos',NULL),
  ('parte','Evidence Previdência',NULL),
  ('parte','EPB',NULL),
  ('parte','F. Cafe',ARRAY['F. Café']),
  ('parte','FIRST',ARRAY['F1RST']),
  ('parte','Fundação Santander',NULL),
  ('parte','Fundação Sudameris',NULL),
  ('parte','Getnet',NULL),
  ('parte','Getnet Adquirência',NULL),
  ('parte','Instituto Escola Brasil',NULL),
  ('parte','Integry Tecnologia',NULL),
  ('parte','Isban Brasil',NULL),
  ('parte','Izzettle',ARRAY['Izettle']),
  ('parte','Norchem',NULL),
  ('parte','Norchem Holdings',NULL),
  ('parte','Norchem Participações',NULL),
  ('parte','ODC Ambievo Tecnologia',NULL),
  ('parte','Olé Bonsucesso',NULL),
  ('parte','Produban',NULL),
  ('parte','Pulse',NULL),
  ('parte','RETURN',NULL),
  ('parte','Ridup',NULL),
  ('parte','ROJO',NULL),
  ('parte','ROJO ENTRETENIMENTO',NULL),
  ('parte','Sam Brasil',NULL),
  ('parte','Sancap',NULL),
  ('parte','Sanprev',NULL),
  ('parte','SANB Promotora',NULL),
  ('parte','Santander',NULL),
  ('parte','Santanderprevi',NULL),
  ('parte','SI DISTRIBUIDORA',NULL),
  ('parte','Sudameris',NULL),
  ('parte','Super Pagamentos e Administração de Meios Eletrônicos',NULL),
  ('parte','SX Negócios',NULL),
  ('parte','SX TOOLS',NULL),
  ('parte','TECBAN',NULL),
  ('parte','Toque Fale',NULL),
  ('parte','Universia Brasil',NULL),
  ('parte','Virtual Motors',NULL),
  ('parte','Virtual Motors Páginas Eletrônicas',NULL),
  ('parte','Webmotors',NULL),
  ('parte','Zurich',NULL),
  ('parte','Zurich Santander Brasil Seguros S.A.',NULL)
) AS t(tipo, termo, termos_or);
