
ALTER TABLE public.processos
  ADD COLUMN IF NOT EXISTS dossie_tst text,
  ADD COLUMN IF NOT EXISTS equipe_tst text,
  ADD COLUMN IF NOT EXISTS relator_tst text,
  ADD COLUMN IF NOT EXISTS relator_favorabilidade text,
  ADD COLUMN IF NOT EXISTS turma_tst text,
  ADD COLUMN IF NOT EXISTS turma_favorabilidade text,
  ADD COLUMN IF NOT EXISTS parte_recorrente_tst text,
  ADD COLUMN IF NOT EXISTS tipo_recurso_reclamante text,
  ADD COLUMN IF NOT EXISTS materias_recurso_reclamante text,
  ADD COLUMN IF NOT EXISTS aparelhamento_reclamante text,
  ADD COLUMN IF NOT EXISTS chance_exito_reclamante text,
  ADD COLUMN IF NOT EXISTS tipo_recurso_banco text,
  ADD COLUMN IF NOT EXISTS materias_recurso_banco text,
  ADD COLUMN IF NOT EXISTS aparelhamento_banco text,
  ADD COLUMN IF NOT EXISTS chance_exito_banco text,
  ADD COLUMN IF NOT EXISTS honra_tst text,
  ADD COLUMN IF NOT EXISTS tema_tst text,
  ADD COLUMN IF NOT EXISTS execucao_tst text,
  ADD COLUMN IF NOT EXISTS midia_negativa_tst text,
  ADD COLUMN IF NOT EXISTS decisao_quarteirizado text,
  ADD COLUMN IF NOT EXISTS recurso_terceiros_tst text,
  ADD COLUMN IF NOT EXISTS benner_atualizado boolean;
