
-- Carlos Jose Elias Junior - Coordenação Santander Trabalhista
INSERT INTO monitoramentos_djen (
  coordenacao_id, tipo, termo_busca, oab, uf, ativo, criado_por, exclusoes, tribunais
) VALUES (
  '70d3e1ba-70ff-46d0-a6cf-4d4b553d324a',
  'advogado',
  'CARLOS JOSE ELIAS JUNIOR',
  '10424',
  'DF',
  true,
  'a318c5eb-c2cc-480a-952a-5c2a42b85fc6',
  ARRAY['PROFORTE S/A TRANSPORTE DE VALORES','GOL LINHAS AEREAS S.A.','HOSPITAL SANTA LUCIA S/A','OCEANAIR LINHAS AÉREAS S.A.','SERVICO DE APOIO AS MICRO E PEQUENAS EMPRESAS DO ESTADO DE GOIAS','UNIAO QUIMICA FARMACEUTICA NACIONAL S A','F & F DISTRIBUIDORA DE PRODUTOS FARMACEUTICOS LTDA','CREFISA SA CREDITO FINANCIAMENTO E INVESTIMENTO','ADOBE ASSESSORIA DE SERVIÇOS CADASTRAIS S.A','OTAVIO NORONHA SOCIEDADE INDIVIDUAL DE ADVOCACIA','GOL TRANSPORTES AEREOS S.A.','GOL LINHAS AÉREAS','HOSPITAL DE MEDICINA ESPECIALIZADA LTDA','VIACAO PIRACICABANA S.A.','CEVEL CECILIO VEICULOS LTDA','CONCEPT AEROPORTO','HOSPITAL SANTA LUZIA S A','MINERVA S.A','HEINZ BRASIL S.A.','REDE D''OR SAO LUIZ S.A','PROTEGE S/A PROTECAO E TRANSPORTE DE VALORES','UNICOM MARISTA PRODUTOS PROFISSIONAIS LTDA','CLINICA DE CAMPO GRANDE S/A','BRADESCO VIDA E PREVIDÊNCIA','HOSPITAIS INTEGRADOS DA GAVEA S/A','HOSPITAL MARIA AUXILIADORA S/A','BANCO CITIBANK S A','ANIMA CENTRO HOSPITALAR LTDA','HOSPITAL PRONTONORTE S/A'],
  ARRAY['TJMT','TJRO','TJAC','TJMS','TJRR','TJAP','TJPA','TJAM','TJTO','TJDFT','TJGO','TJRS','STJ','STF','TST']
);

-- Osmar Mendes Paixão Cortes - Coordenação Santander Trabalhista
INSERT INTO monitoramentos_djen (
  coordenacao_id, tipo, termo_busca, oab, uf, ativo, criado_por, exclusoes, tribunais
) VALUES (
  '70d3e1ba-70ff-46d0-a6cf-4d4b553d324a',
  'advogado',
  'OSMAR MENDES PAIXAO CORTES',
  '15553',
  'DF',
  true,
  'a318c5eb-c2cc-480a-952a-5c2a42b85fc6',
  ARRAY['HOSPITAIS INTEGRADOS DA GAVEA S/A','CLINICA DE CAMPO GRANDE S/A','HOSPITAL SANTA LUZIA S A','BRADESCO VIDA E PREVIDÊNCIA','HEINZ BRASIL S.A.','OTAVIO NORONHA SOCIEDADE INDIVIDUAL DE ADVOCACIA','GOL LINHAS AEREAS S.A.','F & F DISTRIBUIDORA DE PRODUTOS FARMACEUTICOS LTDA','PROTEGE S/A PROTECAO E TRANSPORTE DE VALORES','SERVICO DE APOIO AS MICRO E PEQUENAS EMPRESAS DO ESTADO DE GOIAS','PROFORTE S/A TRANSPORTE DE VALORES','CONCEPT AEROPORTO','UNICOM MARISTA PRODUTOS PROFISSIONAIS LTDA','HOSPITAL MARIA AUXILIADORA S/A','VIACAO PIRACICABANA S.A.','HOSPITAL DE MEDICINA ESPECIALIZADA LTDA','GOL TRANSPORTES AEREOS S.A.','OCEANAIR LINHAS AÉREAS S.A.','UNIAO QUIMICA FARMACEUTICA NACIONAL S A','CREFISA SA CREDITO FINANCIAMENTO E INVESTIMENTO','CEVEL CECILIO VEICULOS LTDA','ADOBE ASSESSORIA DE SERVIÇOS CADASTRAIS S.A','HOSPITAL SANTA LUCIA S/A','ANIMA CENTRO HOSPITALAR LTDA','BANCO CITIBANK S A','HOSPITAL PRONTONORTE S/A','REDE D''OR SAO LUIZ S.A','GOL LINHAS AÉREAS','MINERVA S.A'],
  ARRAY['TJMT','TJRO','TJAC','TJMS','TJRR','TJAP','TJPA','TJAM','TJTO','TJDFT','TJGO','TJRS','STJ','STF','TST']
);
