TRUNCATE TABLE public.materias_benner RESTART IDENTITY CASCADE;

INSERT INTO public.materias_benner (nome, descricao) VALUES
('Abono Assiduidade', 'Reclamante alega que não foi concedida a folga assiduidade prevista na CCT dos bancários. O pedido é feito por empregados do banco ou por terceiros que pedem enquadramento bancário ou vínculo de emprego com o Banco por ilicitude da terceirização'),
('Adicional de Insalubridade', 'Reclamante pede o pagamento de adicional de insalubridade (ex.: ruído, calor, radiação, agentes químicos, tolerância, frio, umidade, etc)'),
('Adicional de Penosidade', 'Reclamante pede o pagamento de adicional de penosidade (exposição a condições penosas)'),
('Adicional de Periculosidade', 'Reclamante pede o pagamento de adicional de periculosidade por motivo diferente de exposição a óleo diesel (e respectivos geradores / tanques).'),
('Adicional de Periculosidade - Óleo Diesel', 'Reclamante pede o pagamento de adicional de periculosidade por exposição a óleo diesel (e respectivos geradores / tanques) em qual local diferente da Torre Santander JK, Santander Cultural, Paulista, Casa 1 (Radar), Casa 2, Casa 3 (Geração Digital) e Brigadeiro.'),
('Adicional de Periculosidade - Óleo Diesel - Casa 1', 'Reclamante pede o pagamento de adicional de periculosidade por exposição a óleo diesel (e respectivos geradores / tanques) no Radar / Casa 1'),
('Adicional de Periculosidade - Óleo Diesel - Casa 2', 'Reclamante pede o pagamento de adicional de periculosidade por exposição a óleo diesel (e respectivos geradores / tanques) no Casa 2'),
('Adicional de Periculosidade - Óleo Diesel - Casa 3', 'Reclamante pede o pagamento de adicional de periculosidade por exposição a óleo diesel (e respectivos geradores / tanques) no Geração Digital / Casa 3'),
('Adicional de Periculosidade - Óleo Diesel - Paulista', 'Reclamante pede o pagamento de adicional de periculosidade por exposição a óleo diesel (e respectivos geradores / tanques) no prédio da Avenida Paulista'),
('Adicional de Periculosidade - Óleo Diesel - Santander Cultural', 'Reclamante pede o pagamento de adicional de periculosidade por exposição a óleo diesel (e respectivos geradores / tanques) no Santander Cultural.'),
('Adicional de Periculosidade - Óleo Diesel - Torre Santander', 'Reclamante pede o pagamento de adicional de periculosidade por exposição a óleo diesel (e respectivos geradores / tanques) na Torre Santander / JK.'),
('Adicional de Risco', 'Reclamante pede o pagamento de adicional de risco porque fazia transporte de valores'),
('Adicional de Transferência', 'Reclamante pede o pagamento de adicional por ter sido transferido de seu local de trabalho'),
('Adicional por Tempo de Serviço', 'Reclamante pede o pagamento de adicional por tempo de serviço previsto na CCT dos bancários'),
('Assistência judiciária gratuita', 'Reclamante pede isenção de custas por ser beneficiário da justiça gratuita'),
('Aporte para reforço da reserva matemática', 'Pagamento de diferenças de contribuição para o plano em razão de alteração da base de cálculo do benefício de complementação de aposentadoria.'),
('Ausência de Representatividade - Nulidade da Alteração do Regulamento 2009 - Santanderprevi', 'Reconhecimento de nulidade da alteração de regulamento de 2009, com ou sem o pagamento de diferenças de contribuição.'),
('Complementação de Aposentadoria - Diferenças do reajuste de 7,73% ACT 2003', 'Reclamante pede a aplicação do reajuste no percentual de 7,73% e/ou abono pago aos empregados ativos em seu benefício de complementação de aposentadoria.'),
('Complementação de Aposentadoria - FASASS', NULL),
('Complementação de Aposentadoria - Fundação Clemente de Faria', NULL),
('Complementação de Aposentadoria - IAS', NULL),
('Complementação de Aposentadoria - Reajuste pelo IGP-DI', 'Reclamante pede a alteração do índice de reajuste de seu benefício previsto em regulamento para o IGP-DI.'),
('Complementação de Aposentadoria - Reajuste pelo INPC', 'Reclamante pede a alteração do índice de reajuste de seu benefício previsto em regulamento para o INPC.'),
('Complementação de Aposentadoria - Reajustes Indiretos', 'Reclamante pede, genericamente, a aplicação de reajustes concedidos aos empregados da ativa ao seu benefício de complementação de aposentadoria.'),
('Complementação de Aposentadoria - Regulamento de Pessoal - 3,5%', 'Reclamante pede aplicação de reajuste no percentual de 3,5% e/ou abono pago aos empregados ativos concedido aos empregados da ativa em seu benefício de complementação de aposentadoria.'),
('Complementação de Aposentadoria - Regulamento Pessoal - 12,6% + Abono', 'Reclamante pede aplicação de reajuste no percentual de 12,6% e/ou abono pago aos empregados ativos em seu benefício de complementação de aposentadoria.'),
('Complementação de Aposentadoria - Regulamento Pessoal - 5,5 + abono', 'Reclamante pede aplicação de reajuste no percentual de 5,5% e/ou abono concedido aos empregados da ativa em seu benefício de complementação de aposentadoria.'),
('Complementação de Aposentadoria - Regulamento Pessoal - 6,0% + Abono', 'Reclamante pede aplicação de reajuste no percentual de 6,0% e/ou abono pago aos empregados ativos em seu benefício de complementação de aposentadoria.'),
('Complementação de Aposentadoria - Regulamento Pessoal - 7,0% + Abono', 'Reclamante pede aplicação de reajuste no percentual de 7,0% e/ou abono pago aos empregados ativos em seu benefício de complementação de aposentadoria.'),
('Complementação de Aposentadoria - Regulamento Pessoal - 8,5%', 'Reclamante pede aplicação de reajuste no percentual de 8,0% e/ou abono pago aos empregados ativos em seu benefício de complementação de aposentadoria.'),
('Complementação de Aposentadoria Integral', 'Reclamante pede que seja pago benefício de complementação de aposentadoria em sua integralidade sem a aplicação de nenhum fator e/ou  proporcionalidade.'),
('Manutenção Contribuição Holandaprevi', 'Reclamante pede a manutenção da contribuição feita pelo empregador (normalmente o pedido é feito em ações que o reclamante completou 55 anos e há previsão regulamentar interrupção/suspensão/cessação das contribuições)'),
('Pagamento do Plano de Prev.Privada', 'Reclamante alega que o cálculo das contribuições para o plano de previdência estava errado, mas não indica o motivo do pagamento a menor. Em razão disso pede que sejam pagas contribuições e/ou diferenças de contribuição para o plano de aposentadoria'),
('Recálculo da complementação da aposentadoria', 'Reclamante pede que seja alterada a regra de cálculo do benefício de complementação de aposentadoria (alteração da regra de aplicação da proporcionalidade).'),
('Santanderprevi - nulidade da aplicação do regulamento de 2009', 'Reclamante pede que seja reconhecida a nulidade da alteração de regulamento do plano de aposentadoria da Santanderprevi feita em 2009.'),
('Integração do Abono Indenizatório - Clausula 88 ACT 04/06', 'Reclamante pede integração do abono indenizatório previsto na CCT de 04/06 em sua complementação de aposentadoria.'),
('Abono Indenizatório - Cláusula 88ª - ACT 04/06', 'Reclamante pede o pagamento de "Abono" previsto em CCT ou ACT, paga aos ativos e não paga aos aposentados. Normalmente o fundamento do pedido é a previsão de paridade de vencimentos e/ou reajustes entre os empregados da ativa e os aposentados.'),
('Abono indenizatório - Cláusulas 84 (Banco) e 65 (Banespa Serviços) - ACT 01/03', 'Reclamante pede o pagamento dos abonos pagos aos empregados da ativa em virtude do regulamento do plano de aposentadoria prever que o reajuste do benefício segue a mesma regra que dos ativos.'),
('Abono Único - CCT', 'Reclamante pede o pagamento de "Abono" previsto em CCT ou ACT, paga aos ativos e não paga aos aposentados. Normalmente o fundamento do pedido é a previsão de paridade de vencimentos e/ou reajustes entre os empregados da ativa e os aposentados.'),
('Concessão de Complementação de Pensão por Morte', 'Reclamante pede que seja pago benefício de complementação de pensão por morte que não está recebendo.'),
('Diferenças de Contribuição Decorrrentes de Integração de Verbas', 'Reclamante pede o pagamento de diferenças de contribuição em razão de pedido de integração e/ou pagamento de verbas trabalhistas, neste mesmo processo. (não se aplica para Equiparação ou Desvio de Função, e/ou verbas trabalhistas deferidas em ação anterior, pois há pedido próprio para estes casos).'),
('Diferenças de Contribuição Decorrentes de Equiparação e/ou Desvio de Função', 'Reclamante pede o pagamento de diferenças de contribuição em razão de pedido de equiparação e/ou desvio de função, neste mesmo processo. (não se aplica para outros tipos de verbas trabalhistas, e/ou equiparação ou desvio de função deferidas em ação anterior, pois há pedido próprio para estes casos).'),
('Perdas e Danos Decorrrentes de Integração de Verbas', 'Reclamante pede o pagamento de perdas e danos ou diferenças de contribuição em razão de pedido de integração e/ou pagamento de verbas trabalhistas, deferidas em processo anterior.  (Não se aplica para Equiparação ou Desvio de Função, e/ou verbas trabalhistas requeridas nesta ação, pois há pedido próprio para estes casos).'),
('Perdas e Danos Decorrentes de Equiparação e/ou Desvio de Função', 'Reclamante pede o pagamento de perdas e danos ou diferenças de contribuição em razão de pedido de equiparação e/ou desvio de função, deferidas em processo anterior.  (Não se aplica para Equiparação ou Desvio de Função, e/ou verbas trabalhistas requeridas nesta ação, pois há pedido próprio para estes casos).'),
('Diferenças de Contribuição de Verbas Trabalhistas', 'Reclamante pede o pagamento de diferenças de contribuição em razão de verbas trabalhistas não pagas e/ou deferidas na Justiça do Trabalho.'),
('Pagamento e/ou Revisão de Resgate de Contribuições', 'Reclamante pede o pagamento e/ou revisão do valor pago a título de resgate.'),
('Alteração de Índice de Reajuste - Realinhamento', 'Reclamante pede a aplicação de reajustes concedidos a ativos de antigos patrocinadores dos Planos DBA, CACIBAN, IAS e DCA.'),
('Nulidade de Alteração do Custo Médio para Faixa Etária', 'Reclamante pede que seja afastada a aplicação da tabela de faixa etária para a forma de cobrança anterior.'),
('Aplicação de Reajuste da ANS', 'Reclamante pede que sejam aplicados apenas o reajustes autorizados pela ANS em mesmo período e percentual.'),
('Suspensão de Contribuição Extraordinária', 'Reclamante pede a suspensão dos descontos relacionados a Contribuição Extraordinária para o Plano de Aposentadoria.'),
('Devolução de Contribuição Extraordinária', 'Reclamante pede a devolução das Contribuições Extraordinárias recolhidas para o Plano de Aposentadoria.'),
('Suspensão de Descontos', 'Reclamante pede a suspensão de descontos realizados em seu benefício de complementação de aposentadoria (ex. contribuição CABESP, empréstimos, contribuição abesprev, etc).'),
('Devolução de Descontos', 'Reclamante pede a devolução de descontos realizados em seu benefício de complementação de aposentadoria (ex. contribuição CABESP, empréstimos, contribuição abesprev, etc).'),
('Intgração de Verbas Trabalhistas', 'Reclamante pede que seja integrado ao cálculo de seu benefício valor de verbas trabalhistas. (utilizar apenas para os casos em que não há pedido espefícico, tais como, gratificação de função, gratificação de caixa, equiparação salarial, horas extras, desvio de função, comissão de captação, auxílio/cesta-alimentação, ou periculosidade).'),
('Integração de Adicional de Periculosidade', 'Reclamante pede que seja integrado ao cálculo de seu benefício o valor pago enquanto na ativa, requerido nesta ou anterior ação judicial a título de adicional de periculosidade.'),
('Integração do Auxílio-moradia', 'Reclamante pede que seja integrado ao cálculo de seu benefício o valor pago a título de auxílio-moradia enquanto estava na ativa.'),
('Integração de Gratificação de Função', 'Reclamante pede a integração dos valores recebidos a título de gratificação de função no cálculo de seu benefício de complementação de aposentadoria.'),
('Integração de Gratificação de Caixa', 'Reclamante pede a integração dos valores recebidos a título de gratificação de caixa no cálculo de seu benefício de complementação de aposentadoria.'),
('Integração de Equiparação Salarial', 'Reclamante pede que sejam integrado no cálculo de seu benefício valores decorrentes de equiparação salarial.'),
('Integração de Horas Extras', 'Reclamante pede que sejam integrado no cálculo de seu benefício valores decorrentes de horas-extras.'),
('Integração de Desvio de Função', 'Reclamante pede que sejam integrado no cálculo de seu benefício valores decorrentes de desvio de função.'),
('Integração de Gratificação de Dirigente Sindical', 'Reclamante pede que seja integrado no cálculo de seu benefício valores decorrentes da gratificação de dirigente sindical.'),
('Integração de Comissão de Captação', 'Reclamante pede que seja integrado no calculo de seu benefício valores decorrentes da comissão de captação.'),
('Nulidade de Migração entre Planos de Aposentadoria', 'Reclamante pede que seja reconhecida a nulidade da transferência de um plano de aposentadoria para outro foi irregular e deve ser reconhecida a sua nulidade com regresso das parte para a situação anterior.'),
('Concessão de Benefício de Aposentadoria por Idade, Tempo de Serviço e Invalidez', 'Reclamante pede que seja pago benefício de previdência que não está recebendo. (por ex.: Pagamento de complementação de aposentadoria por idade, tempo de serviço ou invalidez)'),
('Pagamento de Gratificação Semestral/PLR', 'Reclamante pede o pagamento de Gratificação Semestral e/ou PLR no mesmo valor pago aos funcionários da ativa.'),
('Integração do Auxílio/Cesta-Alimentação no Benefício de Complementação de Aposentadoria', 'Reclamante pede a integração dos valores recebidos a título de auxilio e cesta-alimentação no cálculo do valor de seu benefício de complementação de aposentadoria.'),
('Restabelecimento de Benefício', 'Reclamante pede que seja restabelecido o pagamento do benefício que vinha recebendo e que foi interrompido/cassado e/ou suspenso, por qualquer motivo. (por ex.: cancelamento do benefício pago pelo INSS; falta de recadastramento ou prova de vida; etc.)'),
('Pagamento de Auxílio/Cesta-Alimentação', 'Reclamante pede o pagamento dos mesmos valores pagos aos empregados da ativa a título de auxilio e cesta-alimentação.'),
('Integração de Promoção Automática', 'Reclamante pede a integração da diferença de salario decorrente de promoção automática no valor de seu benefício de complementação de aposentadoria.'),
('Não Redução do Valor Nominal - INSS', 'Reclamante pede que o valor do benefício não seja reduzido em razão de aumento real concedido pelo INSS e/ou nos casos em que a complementação ou o salário da ativa não teve reajuste e o valor do INSS foi reajustado.'),
('Diferenças salariais - Grade', 'Reclamante alega que deve receber diferenças por enquadramento incorreto na política salarial de Grade (política do Banco Real)'),
('Diferenças salariais - Nível', 'Reclamante alega que deve receber diferenças por enquadramento incorreto na política salarial de níveis'),
('Equiparação salarial em cadeia', 'Reclamante requer a equiparação salarial com paradigma que ganhou equiparação com outro paradigma em outro processo. Exemplo: "A" pede equiparação com "B", que ganhou a equiparação com "C" em outro processo, portanto "A" requer (pela cadeia) o pagamento da equiparação com "C"'),
('Desvio de função', 'Reclamante alega que realizava atividade diferente para qual foi contratada'),
('Equiparação Salarial Corporate', 'Reclamante pede equiparação salarial com empregados da área / departamento Corporate'),
('Equiparação salarial e reflexos', 'Reclamante alega que exercia a mesma atividade, com a mesma perfeição técnica, na mesma região que outro empregado (art. 461 CLT), mas recebia salário menor e, portanto, pede essa diferença de salário.'),
('Gratificação Especial - com paradigma', 'Reclamante alega que o Banco paga gratificação no desligamento e que não recebeu, fazendo jus a esse pagamento. Normalmente junta documentos de outros empregados que receberam na rescisão e apresenta fórmula de cálculo e cita os nomes dos paradigmas na inicial'),
('Gratificação Especial - sem paradigma', 'Reclamante alega que o Banco paga gratificação no desligamento e que não recebeu, fazendo jus a esse pagamento. Normalmente junta documentos de outros empregados que receberam na rescisão, apresenta fórmula de cálculo e NÃO cita os nomes dos paradigmas na inicial'),
('Integração da gratificação de função na hora extra', 'Integração da gratificação de função na base de cálculo da hora extra'),
('Gratificação Aleatória de Balanço', 'Reclamante alega que nunca recebeu ou sofreu a supressão da gratificação aleatória de balanço'),
('Gratificação de Caixa', 'Reclamante alega que exerceu a função de caixa e deveria ter recebido a respectiva gratificação.'),
('Gratificação de Compensador', 'Reclamante pede gratificação do compensador de cheques'),
('Gratificação de Função', 'Reclamante pede enquadramento bancário ou vínculo de emprego e, consequentemente, o pagamento da gratificação de função.'),
('Gratificação semestral convencional', 'Não pagamento (total ou parcial) de gratificação semestral prevista em norma coletiva'),
('Gratificação Semestral Estatutária', 'Não pagamento (total ou parcial) de gratificação semestral prevista em regulamento interno'),
('Integração da gratificação semestral', 'Reclamante pede a integração da gratificação semestral em verbas trabalhistas (ex.: PLR, 13º salário)'),
('Honorários Advocatícios', 'Reclamante pede o pagamento de honorários advocatícios - genérico ou por estar assistido por sindicato (exceto sucumbência e indenização). Pedido genérico normalmente feito antes da Reforma Trabalhista.'),
('Honorários Advocatícios - Indenização', 'Reclamante pede o pagamento de indenização pelos gastos com honorários contratuais de seu advogado'),
('Honorários de Sucumbência', 'Reclamante pede o pagamento de honorários em caso de vitória e, consequentemente, perda (sucumbência) pelo Banco. Pedido baseado na Reforma Trabalhista'),
('Indenização por dano material - Adoecimento mental', 'Reclamante pede indenização por dano material sofrido em razão de adoecimento mental (pressão por metas, ofensas, mecanismos de gestão)'),
('Indenização por dano material - doença/acidente', 'Reclamante pede indenização por dano material sofrido em razão de qualquer acidente ou doença adquirida em razão do trabalho (exceto LER/DORT e adoecimento mental - há objeto próprio)'),
('Indenização por dano moral - Adoecimento mental', 'Reclamante pede indenização por dano moral sofrido em razão de adoecimento mental (pressão por metas, ofensas, mecanismos de gestão)'),
('Indenização por dano moral - doença/acidente', 'Reclamante pede indenização por dano moral sofrido em razão de qualquer acidente ou doença adquirida em razão do trabalho (exceto LER/DORT e adoecimento mental - há objeto próprio)'),
('Indenização por dano material', 'Reclamante pede indenização por dano material. Pedido residual, pois há objeto próprio em caso de qualquer acidente ou doença adquirida em razão do trabalho, LER/DORT e adoecimento mental.'),
('Indenização por dano material - LER/Acidente do Trabalho', 'Reclamante pede indenização por dano material sofrido em razão de LER/DORT'),
('Indenização por dano moral', 'Reclamante pede indenização por dano moral. Pedido residual, pois há objeto próprio em caso de qualquer acidente ou doença adquirida em razão do trabalho; LER/DORT; adoecimento mental; assédio moral; assédio sexual; discriminação.'),
('Indenização por dano moral - assédio moral', 'Reclamante pede indenização em razão de ter sofrido assédio moral (por metas, tratatamento rigoroso do gestor, esvaziamento de função, exposição de metas/Super Ranking, etc)'),
('Indenização por Dano Moral - Assédio Sexual', 'Reclamante pede indenização em razão de ter sofrido assédio sexual no ambiente de trabalho'),
('Indenização por dano moral - LER/Acidente do Trabalho', 'Reclamante pede indenização por dano moral sofrido em razão de LER/DORT'),
('Indenização por danos morais - Discriminação', 'Reclamante pede indenização em razão de ter sofrido discriminação (exemplos de causas da discriminação: gênero, orientação sexual, HIV,câncer, PCD, raça, orientação religiosa, opinião política, etc)'),
('Divisor 150/200', 'Reclamante pede a aplicação do divisor 150/200 nas horas extras'),
('Divisor 180/220', 'Reclamante pede a aplicação do divisor 180/220 nas horas extras'),
('Horas extras 7ª e 8ª - cargo de confiança', 'Reclamante exercia jornada de 8 horas e não estava sujeito a controle de jornada (art. 62 da CLT), e alega que não tinha cargo de confiança'),
('Horas extras 7ª e 8ª - cargo de confiança J8', 'Reclamante exercia jornada de 8 horas e estava sujeito a controle de jornada (art. 224, §2º da CLT), e alega que não tinha cargo de confiança'),
('Horas extras além da 6ª - ponto eletrônico', 'Reclamante com cargo de 6 horas alega que batia ponto incorretamente (começava a trabalhar e batia ponto posteriormente / batia ponto e continuava trabalhando)'),
('Horas extras além da 8ª - cargo de confiança', 'Reclamante não estava sujeito a controle de jornada (art. 62, II da CLT) e alega que não tinha cargo de confiança'),
('Horas extras além da 8ª - ponto eletrônico', 'Reclamante com cargo de 8 horas alega que batia ponto incorretamente (começava a trabalhar e batia ponto posteriormente / batia ponto e continuava trabalhando)'),
('Horas extras - jornada externa', 'Reclamante não estava sujeito a controle de jornada  e realizava atividades externas (art. 62, I da CLT)'),
('Horas extras em viagem', 'Reclamante pede horas extras pois realizava viagens à trabalho fora da jornada normal'),
('Horas extras interjornada', 'Reclamante não usufruiu das 11 horas de descanso entre uma jornada e outra e pede o pagamento de horas extras (pelo período total ou parcial de intervalo não usufruído)'),
('Horas extras intervalo art. 384 (mulher)', 'Reclamante (mulher) pede o pagamento de 15 minutos como extra, por não ter usufruído desse intervalo de 15 minutos antes de começar a fazer horas extras. Eventualmente homens também pedem esse intervalo, alegando que os direitos são iguais aos direitos da mulher.'),
('Horas extras intervalo digitador', 'Reclamante pede horas extras por ter usufruído o intervalo de 10 minutos após 90 minutos contínuos de digitação (art. 72 da CLT)'),
('Horas extras intrajornada', 'Reclamante pede o pagamento do intervalo para almoço não usufruído em todo ou em parte (art. 71 da CLT).'),
('Horas extras sábados e domingos', 'Reclamante pede horas extras por ter trabalhado aos finais de semana e feriados, fora da sua jornada normal de trabalho.'),
('Horas in itinere', 'Reclamante pede horas extras em razão do tempo gasto no deslocamento entre sua casa e trabalho e/ou do trabalho para casa'),
('Adicional Noturno', 'Reclamante alega trabalho durante a hora noturna (entre as 22 hrs e 5 hrs)'),
('Diferenças de horas extras pagas no contrato - Divisor 150/200', 'Reclamante pede o recálculo do divisor incidente sobre as horas extras pagas durante o contrato de trabalho'),
('Horas de sobreaviso e reflexos', 'Reclamante pede horas extras pois ficava à disposição do Banco fora do horário de trabalho, aguardando chamado (via celular, notebook, etc) para desempenhar alguma atividade / trabalho na empresa ou à distância'),
('Horas Extras 7ª e 8ª - Vincendas', 'Reclamante ativo pede que as horas extras (por não exercer cargo de confiança) continuem sendo pagas no futuro, enquanto durar o contrato de trabalho.'),
('Horas Extras além da 4ª e reflexos', 'Reclamante exerceu o cargo de advogado e pede horas extras além da 4ª hora diária trabalhada em razão de não trabalhar com exclusividade para o Banco'),
('Indenização - supressão de horas extras', NULL),
('Nulidade da Pré-Contratação de Horas Extras', 'Reclamante alega que no momento da admissão aderiu a um termo estabelecendo a realização de horas extras habituais e pede a nulidade da contratação'),
('Nulidade dos Acordos de Compensação de Horas', 'Reclamante alega que no momento da admissão aderiu a um termo estabelecendo a possibilidade de compensação de horas extras habituais e pede a nulidade da contratação'),
('Nulidade dos Acordos de Prorrogação de Jornada', 'Reclamante alega que no momento da admissão aderiu um termo estabelecendo a possibilidade de prorrogação da jornada em até 1h50m por dia e requer a sua nulidade'),
('Horas extras -  Campanhas universitárias', 'Reclamante pede horas extras pois participava de campanhas em universidades para angariar clientes de contas universitárias fora de sua jornada de trabalho, nornalmente no período noturno.'),
('Horas extras – cursos online', 'Reclamante pede horas extras pois era obrigado a fazer cursos online fora de sua jornada de trabalho.'),
('Anulação de Justa Causa - Verbas Rescisórias', 'Reclamante pede reversão da Justa Causa e pagamento de vervas rescisórias decorrentes da alteração da modalidade da dispensa'),
('Antecipação de Tutela', 'Reclamante pede a concessão de antecipação de tutela (antecipar a concessão de pedido / pedidos)'),
('Liminar c/c com Multa', 'Reclamante pede a concessão de medida liminar sem multa'),
('Medida Liminar', 'Reclamante pede a concessão de medida liminar sem multa'),
('Multa art. 467 da CLT - pagamento verbas incontroversas', 'Reclamante pede o pagamento de multa caso o Banco não pague as verbas incontroversas na primeira audiência (verbas que não há dúvida se são devidas)'),
('Multa art. 477 da CLT - atraso pagamento rescisão', 'Reclamante pede o pagamento de multa porque as verbas rescisórias não foram pagas / não foram pagas no prazo'),
('Multa', 'Reclamante pede qualquer multa não contemplada nas multas com pedido específico'),
('Multa convencional', 'Reclamante pede o pagamento de multa prevista na CCT pelo descumprimento de sua (s) cláusula (s)'),
('Multa de 40% do FGTS', 'Reclamante pede o pagamento da multa de 40% sobre os depósitos de FGTS, a qual é devida na rescisão do contrato de trabalho por decisão do empregador (dispensa).'),
('Multa por atraso na homologação', 'Reclamante pede o pagamento de multa porque a empresa atrasou a homologação da rescisão do contrato de trabalho'),
('Multa por Descumprimento de Obrigação', 'Reclamante pede multa por descumprimento de obrigação de fazer'),
('Nulidade de Cláusula Convencional', 'Reclamante alega que alguma cláusula da Convenção ou Acordo Coletivo do Trabalho é nula. Não utilizar para outras nulidades que são se relacionam diretamente com a nulidade de cláusula de ACT / CCT.'),
('Nulidade de Termo de Conciliação Prévia', NULL),
('Baixa na CTPS', 'Reclamante pede que o reclamado anote o término do contrato de trabalho (rescisão contratual) em sua carteira de trabalho'),
('Exibição de Documentos', 'Reclamante pede a exibição de documentos (normalmente para ingressar com ação trabalhista, mas o pedido pode ser formulado em ação trabalhista que já contenha outros pedidos).'),
('Expedição de Ofícios ao INSS/DRT', 'Reclamante pede a expedição/emissão de Ofícios ao INSS/DRT/Ministério do Trabalho por suposto descumprimento de obrigações trabalhistas.'),
('Obrigação de Fazer', 'Reclamante pede o cumprimento de obrigação de fazer (excluindo-se aquelas com pedido específico, por ex.: anotação, retificação e baixa na CTPS; exibição de documentos; expedição de ofícios).'),
('Obrigação de Não Fazer', 'Reclamante pede o cumprimento de obrigação de não fazer.'),
('Registro em CTPS', 'Reclamante pede que o reclamado registre o contrato de trabalho em sua carteira de trabalho (normalmente em pedido de reconhecimento de vínculo de emprego, pois não havia a anotação do contrato na CTPS)'),
('Retificação da CTPS', 'Reclamante pede que o reclamado corrija anotações na sua CTPS'),
('Pensão mensal adoecimento mental', 'Reclamante pede o pagamento de pensão mensal em razão de ter sido acometido por adoecimento mental, seja ela com duração vitalícia, seja parcela única ou por expectativa de vida (salvo se o motivo for LER/DORT, pois há pedido próprio).'),
('Pensão mensal LER/DORT', 'Reclamante pede o pagamento de pensão mensal em razão de ter sido acometido por LER/DORT, seja ela com duração vitalícia, seja parcela única ou por expectativa de vida (salvo se o motivo for adoecimento mental, pois há pedido próprio).'),
('Pensão mensal', 'Reclamante pede o pagamento de pensão mensal, seja ela com duração vitalícia, seja parcela única ou por expectativa de vida (salvo se o motivo for LER/DORT ou adoecimento mental, pois há pedido próprio).'),
('Aplicação de reajuste salarial da categoria bancária', 'Reclamante pede a aplicação de reajuste salarial da categoria bancária (normalmente em caso de pedido de reconhecimento de vínculo de emprego ou enquadramento bancário).'),
('Quilômetro rodado', 'Reclamante pede reembolso de despesas com viagens de trabalho'),
('Devolução de descontos', 'Reclamante pede a devolução de descontos efetuados no seu salário ou na rescisão'),
('Pagamento de despesas para aquisição de vestimentas', 'Reclamante pede o pagamento das despesas com vestimentas (roupas, maquiagem, sapatos) determinadas pelo empregador (padrão obrigatório de vestimenta fixado em norma interna da empresa ou determinação do gestor).'),
('Reembolso com despesas de cursos', 'Reclamante pede reembolso de despesas com cursos'),
('Reembolso com despesas de mudança', 'Reclamante pede reembolso com despesas de mudança decorrente de transferência do local de trabalho feita pelo empregador'),
('Reembolso de Despesas com Celular', 'Reclamante pede reembolso de despesas com ligações do celular pessoal para atividades de trabalho'),
('Ressarcimento de despesas com tratamento médico', 'Reclamante pede ressarcimento / reembolso das despesas médicas decorrentes de doença ou acidente de trabalho'),
('Reembolso das diferenças de caixa', 'Reclamante pede a devolução dos valores descontados a título de diferenças de caixa/quebra de caixa'),
('Reintegração por Discriminação', 'Reclamante pede Reintegração decorrente de discriminação em todas as esferas ( idade / racial / gênero / condição social e física)'),
('Reintegração no emprego por estabilidade provisória', 'Reclamante pede Reintegração decorrente de estabilidade provisória na empresa.'),
('Reintegração no emprego por estabilidade previdenciária', 'Reclamante pede  Reintegração decorrente de estabilidade previdenciária, espécie B31, quando ocorre o afastamento por mais de 15 dias e pleiteia o retorno em razão de eventual estabilidade;'),
('Reintegração no emprego por estabilidade pré aposentadoria', 'Reclamante pede Reintegração por estabilidade pré-aposentadoria, decorre da alegada dispensa obstativa de direito,  e não observância da previsão da CCT.'),
('Reintegração no emprego por estabilidade gestante', 'Reclamante pede Reintegração por estabilidade gestante, decorrente da comprovação do estado gravídico, no período ativo ou extensão ao aviso prévio.'),
('Reintegração no emprego por estabilidade dirigente sindical', 'Reclamante pede Reintegração por estabilidade dirigente sindical, quando há reconhecimento previsto / registro sistêmico estabilidade sindical.'),
('Reintegração no emprego por estabilidade dirigente Cooperativa', 'Reclamante pede Reintegração  por estabilidade dirigente cooperativa, decorre do reconhecimento da cooperativa, como ponto a equiparar a mesma estabilidade do dirigente sindical.'),
('Reintegração no emprego por estabilidade cipeiro', 'Reclamante pede Reintegração por estabilidade cipeiro, decorrente de eleição ao cargo do ciperio.'),
('Reintegração no emprego por estabilidade acidentária', 'Reclamante pede Reintegração decorrente de estabilidade acidentária, espécie B91, quando decorrente de acidente trabalho.'),
('Reintegração no emprego por estabilidade - Regulamento de Pessoal', 'Reclamante pede Reintegração por estabilidade - Regulamento de Pessoal decorrente de garantia concedida pelço empregador atra´ves de carta BMG ou estuto Banespa/Meridional.'),
('Reintegração - PCD', 'Reclamante pede Reintegração alegando ser Portador de Necessidades Especiais, ou ausência de susbtituto prévio  ao desligamento.'),
('Reintegração - Lei de greve', 'Reclamante pede Reintegração com fundamento na Lei de greve, que prevê garantia de emprego.'),
('Anulação de Justa Causa - Reintegração', 'Reclamante pede anulação de Justa Causa e também Reintegração (os dois pedidos de forma concomitante na mesma ação).'),
('Devolução de descontos de seguro de vida', 'Reclamante pede a devolução dos descontos de seguro de vida descontados no curso do contrato de trabalho (por exemplo: alega que não fez a adesão livremente e que o desconto foi compulsório)'),
('Integração PPE', 'Reclamante pede diferenças de pagamento de Programa Próprio de Específico (PPE) mediante o reconhecimento da natureza salarial'),
('Integração do salário in natura', 'Reclamante pede a integração de utilidades no salário (ex.: veículo fornecido pela empresa, notebook, celular, etc). Não utilizar para pedidos específicos de integração (ex.: cesta alimentação, vale refeição).'),
('Salário família', 'Reclamante pede o pagamento do salário família (por ex.: terceiro que alega que o real empregador nunca concedeu o salário família).'),
('Salário maternidade', 'Reclamante pede o pagamento do salário maternidade (ex.: ação de reintegração em razão da reclamante estar gestante, na qual ela pede a indenização substitutiva à reintegração pelo período da garantia de emprego / estabilidade).'),
('Salário substituição', 'Reclamante alega que substituiu outro empregado da empresa, que recebia salário maior que o seu, e pede o pagamento da diferença entre o seu salário e do paradigma pelo período da substituição.'),
('Seguro de Vida', 'Reclamante tinha seguro de vida pela empresa (empregador) e a Zurich era estipulante.'),
('Vale Cultura', 'Reclamante pede o pagamento de vale cultura, com base na Lei e/ou Convenção Coletiva de Trabalho (por exemplo: reconhecimento de vínculo (terceiro ou estagiário) / enquadramento bancário).'),
('Vale transporte', 'Reclamante pede reconhecimento de vínculo (terceiro ou estagiário) / enquadramento bancário e pleiteia o pagamento de vale transporte (por exemplo: pela previsão da CCT; por não ter recebido da real empregadora; ou não aponta outro fundamento além da ilegalidade da terceirização). Reclamante é bancário e alega que não foi concedido o vale-transporte, que foi negado ou suprimido.'),
('Ajuda Alimentação', 'Reclamante pede reconhecimento de vínculo (terceiro ou estagiário) / enquadramento bancário e pleiteia o pagamento de ajuda alimentação; por não ter recebido da real empregadora; ou não aponta outro fundamento além da ilegalidade da terceirização. Reclamante é bancário e alega que não foi concedida a ajuda alimentação, que foi negada ou suprimida.'),
('Ajuda Alimentação no Aviso Prévio Indenizado', 'Reclamante pede que seja considerada a projeção do aviso prévio, ainda que indenizado, para pagamento da ajuda alimentação (VA/VR)'),
('Ajuda de Custo', 'Reclamante pede o pagamento de ajuda de custo, alegando trata-se de verba salarial paga há alguns empregados (falta de igualdade / isonomia)'),
('Ajuda Deslocamento', 'Reclamante pede o pagamento de ajuda deslocamento para o período noturno'),
('Assistência Médica', 'Reclamante pede a manutenção do plano de saúde enquanto perdurar a incapacidade laborativa e a estabilidade; direito de manutenção após o desligamento ou alteração lesiva do plano de saúde'),
('Assistência Odontológica', 'Reclamante pede a manutenção do plano odontológico enquanto perdurar a incapacidade laborativa e a estabilidade ou direito de manutenção após o desligamento'),
('Auxílio Cesta Alimentação', 'Reclamante pede o pagamento de auxílio cesta alimentação conforme CCT; reconhecimento de vínculo (estagiário ou terceiro)  / enquadramento bancário e pleiteia o pagamento de cesta alimentação; por não ter recebido da real empregadora; ou não aponta outro fundamento além da ilegalidade da terceirização. Reclamante é bancário e alega que não foi concedida a cesta alimentação, que foi negada ou suprimida.'),
('Auxílio Combustível', 'Reclamante pede o pagamento de auxílio combustível para cobrir o gasto das visitas com veículo próprio'),
('Auxílio Educação', 'Reclamante pede o pagamento de auxílio educação previsto em norma interna'),
('Auxílio Funeral', 'Reclamante pede pagamento de auxílio funeral conforme previsão da CCT, alegando que o auxílio não foi concedido, que foi negado ou suprimido.'),
('Auxílio Moradia', 'Reclamante pede diferenças de auxílio moradia (alegada redução) ou pede integração da verba ao salário'),
('Cesta Alimentação Adicional - CCT 2004/2005', 'Reclamante pede o pagamento da cesta alimentação adicional prevista na CCT de 2004/2005'),
('Complementação do auxílio doença', 'Reclamante pede o pagamento da complementação do auxílio doença, conforme previsão da CCT, alegando que o auxílio não foi concedido, que foi negado ou suprimido'),
('Integração da ajuda alimentação', 'Reclamante pede o reconhecimento da ajuda alimentação como verba salarial e pede a integração no salário'),
('Integração da cesta alimentação', 'Reclamante pede o reconhecimento da cesta alimentação como verba salarial e pede a integração no salário'),
('Integração de Ajuda de Custo', 'Reclamante pede o reconhecimento da ajuda de custo como verba salarial e pede a integração no salário'),
('Licença gala', 'Reclamante pede o pagamento de indenização decorrente da não concessão da licença gala'),
('Licença paternidade', 'Reclamante pede o pagamento de indenização decorrente da não concessão da licença paternidade (ex. requereu a licença paternidade e foi negada pelo empregador, ou trabalhou no período da licença paternidade)'),
('Manutenção de Agregados Plano de Saúde', 'Reclamante pede o reconhecimento de estabilidade (via de regra com pedido de reintegração) e requer a manutenção do plano de saúde dos dependentes'),
('Manutenção do Seguro de Vida', 'Reclamante pede o direito à extensão do seguro de vida após a rescisão contratual'),
('Manutenção na Apólice de Seguros em Grupo', 'Reclamante pede a manutenção do seguro de vida em grupo quando há pedido de nulidade da dispensa e a consequente reintegração'),
('Enquadramento como financiário', 'Reclamante de outra categoria sindical pede o enquadramento como financiário e os direitos decorrentes.'),
('Integração da Gratificação de Função ao salário (recebimento por mais de 10 anos)', 'Sindicato pede que seja proibida a supressão da gratificação de função por ter permancido na função por mais de 10 anos (fundamento na alteração do art. 468 da CLT pela reforma trabalhista).'),
('Freqüência livre / Dirigente Sindical', 'Sindicato pede reconhecimento de frequência livre aos dirigentes sindicais.'),
('Contribuição Sindical', 'Sindicato pede o recolhimento da contribuição sindical da categoria'),
('Abstenção de 40% do desconto da contrib. sindical', 'Sindicato pede que a empresa se abstenha de descontar 40% da contribuição sindical'),
('Abstenção de 100% do desconto da contribuição sindical', 'Sindicato pede que a empresa se abstenha de descontar 100% da contribuição sindical'),
('Unicidade contratual', 'Reclamante pede que se reconheça que houve um único vínculo de emprego, ao invés de período como terceiro e outro período como empregado.'),
('Responsabilidade subsidiária', 'Reclamante pede a responsabilidade subsidiária do tomador de serviços.'),
('Responsabilidade solidária', 'Reclamante pede a responsabilidade solidária do tomador de serviços.'),
('Reconhecimento de vínculo empregatício', 'Reclamante alega que a terceirização foi ilícita e pede o reconhecimento de vínculo empregatício'),
('Reconhecimento de vínculo - Menor Aprendiz', 'Reclamante alega que o contrato de aprendizagem foi ilícito e pede o reconhecimento do vínculo de emprego'),
('Reconhecimento de vínculo - Estagiário', 'Reclamante alega que o contrato de estágio foi ilícito e pede o reconhecimento do vínculo de emprego'),
('Enquadramento como bancário', 'Reclamante de outra categoria sindical pede o enquadramento como bancário e os direitos decorrentes.'),
('Diferenças de comissões', 'Reclamante pede diferenças de comissões alegando que o cálculo e o pagamento foram incorretos.'),
('Diferenças de PLR - PEX', 'Reclamante pede a integração das parcelas varíaveis pagas sob a rubrica PLR - PEX'),
('DIFERENÇAS DE PLR PELA INTEGRAÇÃO DA GRATIFICAÇÃO SEMESTRAL', 'Reclamante pede a integração da gratificação semestral na base de cálculo de PLR'),
('Diferenças de SRV e reflexos', 'Reclamante alega o pagamento incorreto da verba, requerendo a apresentação de documentos contábeis da agência para apuração da SRV (normalmente mediante laudo contábil).'),
('Integração da remuneração variável', 'Reclamante pede o reconhecimento da natureza salarial da remuneração variável'),
('Integração de comissões', 'Reclamante pede o reconhecimento da natureza salarial das comissões pagas'),
('Integração de luvas', 'Reclamante pede a integração do valor recebido a título de luvas (bônus de retenção de empregado na empresa quando contratado; cláusula que o obriga a permanecer na empresa por determinado período após a contratação).'),
('Pagamento de bônus integral e reflexos', 'Reclamante pede diferenças de bônus alegando que o pagamento foi incorreto da verba, pois diferente da regra estipulada ou por falta de transparência na apuração.'),
('Participação nos lucros e resultados - PLR', 'Reclamante pede o pagamento de PLR do período de afastamento por acidente de trabalho (não utilizar para reflexos em PLR).'),
('PLR Proporcional', 'Reclamante pede o pagamento de diferenças de PLR proporcionais ao período que trabalhou no ano do término do seu contrato de trabalho, bem como, eventualmente, a projeção do aviso prévio proporcional (não utilizar para reflexos em PLR).'),
('Prêmio', 'Reclamante pede o reconhecimento da natureza salarial dos prêmios, com os respectivos reflexos / integrações.'),
('Programa de Participação nos Resultados - PPR', 'Reclamante pede diferenças de PPR, pois alega que não teve acesso ao demonstrativo de cálculo.'),
('Férias em Dobro', 'Reclamante alega que foi obrigado a vender ou fracionar férias, ou que tirou férias apenas "no papel" (formalmente, mas ficou trabalhando) e pede o pagamento em dobro do período total ou parcialmente não usufruído.'),
('Férias Vencidas', NULL),
('Rescisão indireta', 'Reclamante alega que o empregador não cumpre os deveres contratuais e pede a rescisão do contrato de trabalho por justa causa do empregador (rescisão indireta).'),
('Reversão do pedido de demissão em rescisão indireta', 'Reclamante ingressa com ação de rescisão indireta e o empregador faz o desligamento / término do contrato como se fosse pedido de demissão. Ingressa com nova ação (ou adita a ação de rescisão indireta) e pede que seja revertida a demissão a pedido.'),
('Seguro desemprego', 'Reclamante pede a entrega de guias do seguro desemprego ou o pagamento de indenização substitutiva (por ex.: reversão de justa causa; rescisão indireta).'),
('Verbas rescisórias', 'Reclamante pede o pagamento de verbas rescisórias (por ex.: reversão de justa causa; rescisão indireta).'),
('Indenização por dano moral - Transporte de Valores', 'Reclamante pede indenização por dano moral em razão do transporte de valores'),
('Protesto Interruptivo', 'Reclamante pede a interrupção prescricional'),
('Dedução/Compensação cláusula 5ª ou 11ª CCT', 'A decisão aplica a cláusula 5ª ou 11ª da CCT da dedução/compensação da gratificação de função de forma integral ou modulada'),
('Responsabilidade solidária - grupo econômico', 'Reclamante pede a responsabilidade solidária entre as empresas pertencentes ao grupo Santander'),
('Diferenças salariais - Reflexos de outra ação trabalhista', 'Reclamante pede reflexos de uma ação trabalhista na outra'),
('FGTS', 'Reclamante alega que o Banco não depositou o FGTS durante um período ou recolheu de forma indevida.'),
('PLR Adicional', 'Reclamante pede o pagamento do adicional de PLR a partir de 2013 previsto em CCT (não utilizar para reflexos em PLR).'),
('Indenização por dano moral - quebra de sigilo bancário', 'Reclamante pede a indenização por dano moral em razão da quebra de sigilo bancário'),
('Horas extras além 6ª - Estagiário', 'Reclamante era estagiário e pede horas extras além da 6ª por extrapolar a jornada contratual'),
('Diferença de PLR', 'Reclamante pede diferenças no pagamento de PLR por incorreção nos pagamentos (não utilizar para reflexos em PLR ou pagamento de PLR do período de afastamento por acidente de trabalho, pois há pedidos próprios).'),
('Incorporação da gratificação-redução de jornada (8h para 6h)', 'Reclamante requer que o banco não exclua a gratificação de função da remuneração'),
('Reconhecimento de vínculo empregatício - grupo econômico/coligada', 'Reclamante pede o reconhecimento de vínculo entre as empresas pertencentes ao grupo Santander'),
('Reembolso – Home Office', 'Reclamante pede reembolso de despesas pelo trabalho em Home Office'),
('Indenização da estabilidade', 'Reclamante requer o pagamento de indenização correspondente ao período de estabilidade'),
('Multa por Embargos de Declaração', 'Banco condenado ao pagamento de multa por embargos protelatórios'),
('Horas extras 7ª e 8ª - cargo de confiança teletrabalho', 'Reclamante exercia jornada de 8 horas e não estava sujeito a controle de jornada (art. 62, III da CLT), e alega que não tinha cargo de confiança'),
('Horas extras além da 8ª - cargo de confiança teletrabalho', 'Reclamante não estava sujeito a controle de jornada (art. 62, III da CLT) e alega que não tinha cargo de confiança');