INSERT INTO public.materias_benner (nome, descricao) VALUES
('Abono Assiduidade', 'Reclamante alega que não foi concedida a folga assiduidade prevista na CCT dos bancários. O pedido é feito por empregados do banco ou por terceiros que pedem enquadramento bancário ou vínculo de emprego com o Banco por ilicitude da terceirização'),
('Adicional de Insalubridade', 'Reclamante pede o pagamento de adicional de insalubridade (ex.: ruído, calor, radiação, agentes químicos, tolerância, frio, umidade, etc)'),
('Adicional de Penosidade', 'Reclamante pede o pagamento de adicional de penosidade (exposição a condições penosas)'),
('Adicional de Periculosidade', 'Reclamante pede o pagamento de adicional de periculosidade por motivo diferente de exposição a óleo diesel (e respectivos geradores / tanques).'),
('Adicional de Periculosidade - Óleo Diesel', 'Reclamante pede o pagamento de adicional de periculosidade por exposição a óleo diesel (e respectivos geradores / tanques) em qual local diferente da Torre Santander JK, Santander Cultural, Paulista, Casa 1 (Radar), Casa 2, Casa 3 (Geração Digital) e Brigadeiro.'),
('Adicional de Periculosidade - Óleo Diesel - Casa 1', 'Reclamante pede o pagamento de adicional de periculosidade por exposição a óleo diesel (e respectivos geradores / tanques) no Radar / Casa 1'),
('Adicional de Periculosidade - Óleo Diesel - Casa 2', 'Reclamante pede o pagamento de adicional de periculosidade por exposição a óleo diesel (e respectivos geradores / tanques) no Casa 2'),
('Adicional de Periculosidade - Óleo Diesel - Casa 3', 'Reclamante pede o pagamento de adicional de periculosidade por exposição a óleo diesel (e respectivos geradores / tanques) no Geração Digital / Casa 3'),
('Adicional de Periculosidade - Óleo Diesel - Paulista', 'Reclamante pede o pagamento de adicional de periculosidade por exposição a óleo diesel (e respectivos geradores / tanques) no prédio da Avenida Paulista'),
('Adicional de Periculosidade - Óleo Diesel - Santander Cultural', 'Reclamante pede o pagamento de adicional de periculosidade por exposição a óleo diesel (e respectivos geradores / tanques) no Santander Cultural.'),
('Adicional de Periculosidade - Óleo Diesel - Torre Santander', 'Reclamante pede o pagamento de adicional de periculosidade por exposição a óleo diesel (e respectivos geradores / tanques) na Torre Santander / JK.'),
('Adicional de Risco', 'Reclamante pede o pagamento de adicional de risco porque fazia transporte de valores'),
('Adicional de Transferência', 'Reclamante pede o pagamento de adicional por ter sido transferido de seu local de trabalho'),
('Adicional por Tempo de Serviço', 'Reclamante pede o pagamento de adicional por tempo de serviço previsto na CCT dos bancários'),
('Assistência judiciária gratuita', 'Reclamante pede isenção de custas por ser beneficiário da justiça gratuita'),
('Aporte para reforço da reserva matemática', 'Pagamento de diferenças de contribuição para o plano em razão de alteração da base de cálculo do benefício de complementação de aposentadoria.'),
('Ausência de Representatividade - Nulidade da Alteração do Regulamento 2009 - Santanderprevi', 'Reconhecimento de nulidade da alteração de regulamento de 2009, com ou sem o pagamento de diferenças de contribuição.'),
('Complementação de Aposentadoria - Diferenças do reajuste de 7,73% ACT 2003', 'Reclamante pede a aplicação do reajuste no percentual de 7,73% e/ou abono pago aos empregados ativos em seu benefício de complementação de aposentadoria.'),
('Complementação de Aposentadoria - FASASS', NULL),
('Complementação de Aposentadoria - Fundação Clemente de Faria', NULL),
('Complementação de Aposentadoria - IAS', NULL),
('Complementação de Aposentadoria - Reajuste pelo IGP-DI', 'Reclamante pede a alteração do índice de reajuste de seu benefício previsto em regulamento para o IGP-DI.'),
('Complementação de Aposentadoria - Reajuste pelo INPC', 'Reclamante pede a alteração do índice de reajuste de seu benefício previsto em regulamento para o INPC.'),
('Complementação de Aposentadoria - Reajustes Indiretos', 'Reclamante pede, genericamente, a aplicação de reajustes concedidos aos empregados da ativa ao seu benefício de complementação de aposentadoria.'),
('Complementação de Aposentadoria - Regulamento de Pessoal - 3,5%', 'Reclamante pede aplicação de reajuste no percentual de 3,5% e/ou abono pago aos empregados ativos concedido aos empregados da ativa em seu benefício de complementação de aposentadoria.'),
('Complementação de Aposentadoria - Regulamento Pessoal - 12,6% + Abono', 'Reclamante pede aplicação de reajuste no percentual de 12,6% e/ou abono pago aos empregados ativos em seu benefício de complementação de aposentadoria.'),
('Complementação de Aposentadoria - Regulamento Pessoal - 5,5 + abono', 'Reclamante pede aplicação de reajuste no percentual de 5,5% e/ou abono concedido aos empregados da ativa em seu benefício de complementação de aposentadoria.'),
('Complementação de Aposentadoria - Regulamento Pessoal - 6,0% + Abono', 'Reclamante pede aplicação de reajuste no percentual de 6,0% e/ou abono pago aos empregados ativos em seu benefício de complementação de aposentadoria.'),
('Complementação de Aposentadoria - Regulamento Pessoal - 7,0% + Abono', 'Reclamante pede aplicação de reajuste no percentual de 7,0% e/ou abono pago aos empregados ativos em seu benefício de complementação de aposentadoria.'),
('Complementação de Aposentadoria - Regulamento Pessoal - 8,5%', 'Reclamante pede aplicação de reajuste no percentual de 8,0% e/ou abono pago aos empregados ativos em seu benefício de complementação de aposentadoria.'),
('Complementação de Aposentadoria Integral', 'Reclamante pede que seja pago benefício de complementação de aposentadoria em sua integralidade sem a aplicação de nenhum fator e/ou  proporcionalidade.'),
('Manutenção Contribuição Holandaprevi', 'Reclamante pede a manutenção da contribuição feita pelo empregador (normalmente o pedido é feito em ações que o reclamante completou 55 anos e há previsão regulamentar interrupção/suspensão/cessação das contribuições)'),
('Pagamento do Plano de Prev.Privada', 'Reclamante alega que o cálculo das contribuições para o plano de previdência estava errado, mas não indica o motivo do pagamento a menor. Em razão disso pede que sejam pagas contribuições e/ou diferenças de contribuição para o plano de aposentadoria'),
('Recálculo da complementação da aposentadoria', 'Reclamante pede que seja alterada a regra de cálculo do benefício de complementação de aposentadoria (alteração da regra de aplicação da proporcionalidade).'),
('Santanderprevi - nulidade da aplicação do regulamento de 2009', 'Reclamante pede que seja reconhecida a nulidade da alteração de regulamento do plano de aposentadoria da Santanderprevi feita em 2009.'),
('Integração do Abono Indenizatório - Clausula 88 ACT 04/06', 'Reclamante pede integração do abono indenizatório previsto na CCT de 04/06 em sua complementação de aposentadoria.'),
('Abono Indenizatório - Cláusula 88ª - ACT 04/06', 'Reclamante pede o pagamento de "Abono" previsto em CCT ou ACT, paga aos ativos e não paga aos aposentados. Normalmente o fundamento do pedido é a previsão de paridade de vencimentos e/ou reajustes entre os empregados da ativa e os aposentados.'),
('Abono indenizatório - Cláusulas 84 (Banco) e 65 (Banespa Serviços) - ACT 01/03', 'Reclamante pede o pagamento dos abonos pagos aos empregados da ativa em virtude do regulamento do plano de aposentadoria prever que o reajuste do benefício segue a mesma regra que dos ativos.'),
('Abono Único - CCT', 'Reclamante pede o pagamento de "Abono" previsto em CCT ou ACT, paga aos ativos e não paga aos aposentados. Normalmente o fundamento do pedido é a previsão de paridade de vencimentos e/ou reajustes entre os empregados da ativa e os aposentados.'),
('Concessão de Complementação de Pensão por Morte', 'Reclamante pede que seja pago benefício de complementação de pensão por morte que não está recebendo.'),
('Diferenças de Contribuição Decorrrentes de Integração de Verbas', 'Reclamante pede o pagamento de diferenças de contribuição em razão de pedido de integração e/ou pagamento de verbas trabalhistas, neste mesmo processo. (não se aplica para Equiparação ou Desvio de Função, e/ou verbas trabalhistas deferidas em ação anterior, pois há pedido próprio para estes casos).'),
('Diferenças de Contribuição Decorrentes de Equiparação e/ou Desvio de Função', 'Reclamante pede o pagamento de diferenças de contribuição em razão de pedido de equiparação e/ou desvio de função, neste mesmo processo. (não se aplica para outros tipos de verbas trabalhistas, e/ou equiparação ou desvio de função deferidas em ação anterior, pois há pedido próprio para estes casos).'),
('Perdas e Danos Decorrrentes de Integração de Verbas', 'Reclamante pede o pagamento de perdas e danos ou diferenças de contribuição em razão de pedido de integração e/ou pagamento de verbas trabalhistas, deferidas em processo anterior.  (Não se aplica para Equiparação ou Desvio de Função, e/ou verbas trabalhistas requeridas nesta ação, pois há pedido próprio para estes casos).'),
('Perdas e Danos Decorrentes de Equiparação e/ou Desvio de Função', 'Reclamante pede o pagamento de perdas e danos ou diferenças de contribuição em razão de pedido de equiparação e/ou desvio de função, deferidas em processo anterior.  (Não se aplica para Equiparação ou Desvio de Função, e/ou verbas trabalhistas requeridas nesta ação, pois há pedido próprio para estes casos).'),
('Diferenças de Contribuição de Verbas Trabalhistas', 'Reclamante pede o pagamento de diferenças de contribuição em razão de verbas trabalhistas não pagas e/ou deferidas na Justiça do Trabalho.'),
('Devolução das contribuições para o plano de previdência', 'Reclamante pede a devolução do valor pago a título de contribuição para o plano de aposentadoria.'),
('Pedido de migração para outro plano', 'Reclamante pede a migração para plano de previdência diferente do que está vinculado.'),
('Tutela Antecipada para concessão de aposentadoria', 'Reclamante pede a concessão de tutela antecipada para receber o benefício de complementação de aposentadoria.'),
('PCS - Plano de Cargos e Salários', 'Reclamante alega que o Plano de Cargos e Salários não está sendo cumprido / aplicado e pede o seu enquadramento na função correta com o pagamento das diferenças salariais.'),
('Indenização Adicional - Lei 7.238/84', 'Reclamante pede o pagamento de indenização adicional de 1/12 do salário ao empregado dispensado sem justa causa nos 30 dias que antecedem a data de sua correção salarial.'),
('Indenização por dano moral', 'Reclamante pede a indenização por dano moral, sem indicar o motivo.'),
('Indenização por dano moral - Acidente de Trabalho', 'Reclamante pede a indenização por dano moral em razão de acidente de trabalho.'),
('Indenização por dano moral - Doença ocupacional', 'Reclamante pede a indenização por dano moral em razão de doença ocupacional.'),
('Indenização por dano moral - LER/DORT', 'Reclamante pede a indenização por dano moral em razão de doença ocupacional do tipo LER/DORT.'),
('Indenização por dano moral - Assédio Moral', 'Reclamante pede a indenização por dano moral em razão de assédio moral.'),
('Indenização por dano moral - Assédio Sexual', 'Reclamante pede a indenização por dano moral em razão de assédio sexual.'),
('Indenização por dano moral - Discriminação', 'Reclamante pede a indenização por dano moral em razão de discriminação.'),
('Indenização por dano moral - Revista íntima', 'Reclamante pede a indenização por dano moral em razão de revista íntima.'),
('Indenização por dano material', 'Reclamante pede a indenização por dano material, sem indicar o motivo.'),
('Indenização por dano material - Acidente de Trabalho', 'Reclamante pede a indenização por dano material em razão de acidente de trabalho.'),
('Indenização por dano material - Doença ocupacional', 'Reclamante pede a indenização por dano material em razão de doença ocupacional.'),
('Indenização por dano material - LER/DORT', 'Reclamante pede a indenização por dano material em razão de doença ocupacional do tipo LER/DORT.'),
('Indenização por dano estético', 'Reclamante pede a indenização por dano estético, sem indicar o motivo.'),
('Indenização por dano estético - Acidente de Trabalho', 'Reclamante pede a indenização por dano estético em razão de acidente de trabalho.'),
('Indenização por dano existencial', 'Reclamante pede a indenização por dano existencial.'),
('Pensão Mensal Vitalícia', 'Reclamante pede a pensão mensal vitalícia em razão de doença ocupacional ou acidente de trabalho que causou a redução parcial ou total da capacidade laboral.'),
('Reintegração ao Emprego', 'Reclamante pede a reintegração ao emprego, sem indicar o motivo.'),
('Reintegração ao Emprego - Estabilidade Acidentária', 'Reclamante pede a reintegração ao emprego em razão de estabilidade acidentária.'),
('Reintegração ao Emprego - Estabilidade Pré-aposentadoria', 'Reclamante pede a reintegração ao emprego em razão de estabilidade pré-aposentadoria.'),
('Reintegração ao Emprego - Estabilidade Sindical', 'Reclamante pede a reintegração ao emprego em razão de estabilidade sindical.'),
('Reintegração ao Emprego - Estabilidade Gestante', 'Reclamante pede a reintegração ao emprego em razão de estabilidade gestante.'),
('Reintegração ao Emprego - Estabilidade CIPA', 'Reclamante pede a reintegração ao emprego em razão de estabilidade CIPA.'),
('Reintegração ao Emprego - Doença Ocupacional', 'Reclamante pede a reintegração ao emprego em razão de doença ocupacional.'),
('Reintegração ao Emprego - Reversão de Justa Causa', 'Reclamante pede a reintegração ao emprego em razão da reversão da justa causa.'),
('Reintegração ao Emprego - Reversão de Pedido de Demissão', 'Reclamante pede a reintegração ao emprego em razão da reversão do pedido de demissão.'),
('Reintegração ao Emprego - Dispensa Discriminatória', 'Reclamante pede a reintegração ao emprego em razão de dispensa discriminatória.'),
('Equiparação Salarial', 'Reclamante pede o pagamento de diferenças salariais em razão de equiparação salarial.'),
('Desvio de Função', 'Reclamante pede o pagamento de diferenças salariais em razão de desvio de função.'),
('Acúmulo de Função', 'Reclamante pede o pagamento de diferenças salariais em razão de acúmulo de função.'),
('Promoção por Antiguidade', 'Reclamante pede a promoção por antiguidade prevista na CCT dos bancários.'),
('Promoção por Merecimento', 'Reclamante pede a promoção por merecimento prevista na CCT dos bancários.'),
('Auxílio Alimentação', 'Reclamante pede o pagamento de auxílio alimentação ou diferenças de auxílio alimentação.'),
('Auxílio Cesta Alimentação', 'Reclamante pede o pagamento de auxílio cesta alimentação ou diferenças de auxílio cesta alimentação.'),
('Auxílio Refeição', 'Reclamante pede o pagamento de auxílio refeição ou diferenças de auxílio refeição.'),
('Auxílio Educação', 'Reclamante pede o pagamento de auxílio educação ou diferenças de auxílio educação.'),
('Auxílio Creche', 'Reclamante pede o pagamento de auxílio creche ou diferenças de auxílio creche.'),
('Auxílio Babá', 'Reclamante pede o pagamento de auxílio babá ou diferenças de auxílio babá.'),
('Auxílio Funeral', 'Reclamante pede o pagamento de auxílio funeral.'),
('Auxílio Doença', 'Reclamante pede o pagamento de auxílio doença ou diferenças de auxílio doença.'),
('Auxílio Maternidade', 'Reclamante pede o pagamento de auxílio maternidade ou diferenças de auxílio maternidade.'),
('Salário Família', 'Reclamante pede o pagamento de salário família ou diferenças de salário família.'),
('Salário Maternidade', 'Reclamante pede o pagamento de salário maternidade ou diferenças de salário maternidade.'),
('13º Salário', 'Reclamante pede o pagamento de 13º salário ou diferenças de 13º salário.'),
('Férias + 1/3', 'Reclamante pede o pagamento de férias + 1/3 ou diferenças de férias + 1/3.'),
('Férias Vencidas', NULL),
('Férias Proporcionais', 'Reclamante pede o pagamento de férias proporcionais.'),
('Aviso Prévio Indenizado', 'Reclamante pede o pagamento de aviso prévio indenizado.'),
('Aviso Prévio Trabalhado', 'Reclamante pede o pagamento de aviso prévio trabalhado.'),
('Aviso Prévio Proporcional', 'Reclamante pede o pagamento de aviso prévio proporcional ao tempo de serviço.'),
('Multa do Art. 477 da CLT', 'Reclamante pede o pagamento da multa do art. 477 da CLT pelo atraso no pagamento das verbas rescisórias.'),
('Multa do Art. 467 da CLT', 'Reclamante pede o pagamento da multa do art. 467 da CLT pelo não pagamento das verbas incontroversas na primeira audiência.'),
('Multa Convencional', 'Reclamante pede o pagamento de multa convencional prevista em CCT/ACT por descumprimento de cláusula coletiva.'),
('Horas Extras', 'Reclamante pede o pagamento de horas extras, sem indicar o motivo.'),
('Horas Extras - Cargo de Confiança', 'Reclamante pede o pagamento de horas extras alegando que não exercia cargo de confiança.'),
('Horas Extras - Banco de Horas', 'Reclamante pede o pagamento de horas extras alegando irregularidade no banco de horas.'),
('Horas Extras - Compensação de Jornada', 'Reclamante pede o pagamento de horas extras alegando irregularidade na compensação de jornada.'),
('Horas Extras - Intervalo Intrajornada', 'Reclamante pede o pagamento de horas extras pelo não usufruto do intervalo intrajornada.'),
('Horas Extras - Intervalo Interjornada', 'Reclamante pede o pagamento de horas extras pelo não usufruto do intervalo interjornada.'),
('Horas Extras - Intervalo do Art. 384 da CLT', 'Reclamante pede o pagamento de horas extras pelo não usufruto do intervalo do art. 384 da CLT (intervalo da mulher).'),
('Horas Extras - Intervalo do Art. 72 da CLT', 'Reclamante pede o pagamento de horas extras pelo não usufruto do intervalo do art. 72 da CLT (digitadores).'),
('Horas Extras - Sobreaviso', 'Reclamante pede o pagamento de horas extras em regime de sobreaviso.'),
('Horas Extras - Prontidão', 'Reclamante pede o pagamento de horas extras em regime de prontidão.'),
('Horas Extras - DSR', 'Reclamante pede o pagamento de reflexos das horas extras em DSR.'),
('Horas Extras - Reflexos', 'Reclamante pede o pagamento de reflexos das horas extras em outras verbas (férias, 13º, FGTS, etc).'),
('Horas Extras - Adicional Noturno', 'Reclamante pede o pagamento de adicional noturno e/ou horas extras noturnas.'),
('Horas Extras - Hora Noturna Reduzida', 'Reclamante pede o pagamento de horas extras pela não consideração da hora noturna reduzida.'),
('Horas Extras - Tempo à Disposição', 'Reclamante pede o pagamento de horas extras pelo tempo à disposição do empregador.'),
('Horas Extras - Tempo de Deslocamento', 'Reclamante pede o pagamento de horas extras pelo tempo de deslocamento.'),
('Horas Extras - Horas in itinere', 'Reclamante pede o pagamento de horas extras pelo tempo de deslocamento até o local de trabalho (horas in itinere).'),
('Horas Extras - Troca de Uniforme', 'Reclamante pede o pagamento de horas extras pelo tempo gasto na troca de uniforme.'),
('Horas Extras - Reuniões', 'Reclamante pede o pagamento de horas extras pelo tempo gasto em reuniões.'),
('Horas Extras - Treinamentos', 'Reclamante pede o pagamento de horas extras pelo tempo gasto em treinamentos.'),
('Horas Extras - Cursos', 'Reclamante pede o pagamento de horas extras pelo tempo gasto em cursos.'),
('Horas Extras - Login/Logoff', 'Reclamante pede o pagamento de horas extras pelo tempo gasto em login/logoff de sistemas.'),
('Horas Extras - Plantão', 'Reclamante pede o pagamento de horas extras em regime de plantão.'),
('Horas Extras - Feriado', 'Reclamante pede o pagamento de horas extras trabalhadas em feriado.'),
('Horas Extras - Domingo', 'Reclamante pede o pagamento de horas extras trabalhadas em domingo.'),
('Horas Extras - Sábado', 'Reclamante pede o pagamento de horas extras trabalhadas em sábado.'),
('Honorários Advocatícios', 'Reclamante pede o pagamento de honorários advocatícios.'),
('Honorários Periciais', 'Reclamante pede o pagamento de honorários periciais.'),
('Honorários Sucumbenciais', 'Reclamante pede o pagamento de honorários sucumbenciais.'),
('Litigância de Má-fé', 'Reclamante pede a condenação da parte contrária por litigância de má-fé.'),
('Multa por Descumprimento de Sentença', 'Reclamante pede a aplicação de multa por descumprimento de sentença.'),
('Multa por Embargos Protelatórios', 'Reclamante pede a aplicação de multa por embargos protelatórios.'),
('Diferenças Salariais', 'Reclamante pede o pagamento de diferenças salariais, sem indicar o motivo.'),
('Diferenças Salariais - Reajuste', 'Reclamante pede o pagamento de diferenças salariais por aplicação incorreta de reajuste.'),
('Diferenças Salariais - PCS', 'Reclamante pede o pagamento de diferenças salariais por aplicação incorreta do PCS.'),
('Diferenças Salariais - Reflexos', 'Reclamante pede o pagamento de reflexos de diferenças salariais em outras verbas.'),
('Adicional de Função', 'Reclamante pede o pagamento de adicional de função.'),
('Gratificação de Função', 'Reclamante pede o pagamento de gratificação de função.'),
('Gratificação de Função - Incorporação', 'Reclamante pede a incorporação da gratificação de função.'),
('Gratificação de Função - Reflexos', 'Reclamante pede o pagamento de reflexos da gratificação de função.'),
('Gratificação Semestral', 'Reclamante pede o pagamento de gratificação semestral prevista na CCT dos bancários.'),
('Gratificação de Caixa', 'Reclamante pede o pagamento de gratificação de caixa prevista na CCT dos bancários.'),
('Gratificação de Quebra de Caixa', 'Reclamante pede o pagamento de gratificação de quebra de caixa.'),
('Quebra de Caixa', 'Reclamante pede o pagamento de quebra de caixa.'),
('Anuênio', 'Reclamante pede o pagamento de anuênio previsto na CCT dos bancários.'),
('Triênio', 'Reclamante pede o pagamento de triênio.'),
('Quinquênio', 'Reclamante pede o pagamento de quinquênio.'),
('Adicional de Tempo de Serviço', 'Reclamante pede o pagamento de adicional de tempo de serviço.'),
('Vale Transporte', 'Reclamante pede o pagamento ou fornecimento de vale transporte.'),
('Reembolso de Despesas', 'Reclamante pede o reembolso de despesas, sem indicar o motivo.'),
('Reembolso de Despesas - Quilometragem', 'Reclamante pede o reembolso de despesas com quilometragem.'),
('Reembolso de Despesas - Combustível', 'Reclamante pede o reembolso de despesas com combustível.'),
('Reembolso de Despesas - Estacionamento', 'Reclamante pede o reembolso de despesas com estacionamento.'),
('Reembolso de Despesas - Telefone', 'Reclamante pede o reembolso de despesas com telefone.'),
('Reembolso de Despesas - Internet', 'Reclamante pede o reembolso de despesas com internet.'),
('Reembolso de Despesas - Energia Elétrica', 'Reclamante pede o reembolso de despesas com energia elétrica (teletrabalho/home office).'),
('Reembolso de Despesas - Material de Escritório', 'Reclamante pede o reembolso de despesas com material de escritório.'),
('Reembolso de Despesas - Equipamentos', 'Reclamante pede o reembolso de despesas com equipamentos (cadeira, mesa, computador, etc).'),
('Indenização por Uso de Veículo Próprio', 'Reclamante pede a indenização pelo uso de veículo próprio para o trabalho.'),
('Indenização por Uso de Telefone Próprio', 'Reclamante pede a indenização pelo uso de telefone próprio para o trabalho.'),
('Indenização por Uso de Imagem', 'Reclamante pede a indenização pelo uso de imagem.'),
('Indenização por Uso de Nome', 'Reclamante pede a indenização pelo uso de nome.'),
('Indenização - supressão de horas extras', NULL),
('Indenização Substitutiva do Plano de Saúde', 'Reclamante pede a indenização substitutiva do plano de saúde.'),
('Restabelecimento do Plano de Saúde', 'Reclamante pede o restabelecimento do plano de saúde.'),
('Manutenção do Plano de Saúde', 'Reclamante pede a manutenção do plano de saúde após o término do contrato de trabalho.'),
('Custeio do Plano de Saúde', 'Reclamante pede o custeio do plano de saúde pela empresa.'),
('Diferenças de Plano de Saúde', 'Reclamante pede o pagamento de diferenças de plano de saúde.'),
('Restituição de Descontos', 'Reclamante pede a restituição de descontos efetuados em seu salário.'),
('Restituição de Descontos - Plano de Saúde', 'Reclamante pede a restituição de descontos efetuados em seu salário a título de plano de saúde.'),
('Restituição de Descontos - Plano Odontológico', 'Reclamante pede a restituição de descontos efetuados em seu salário a título de plano odontológico.'),
('Restituição de Descontos - Seguro de Vida', 'Reclamante pede a restituição de descontos efetuados em seu salário a título de seguro de vida.'),
('Restituição de Descontos - Empréstimo Consignado', 'Reclamante pede a restituição de descontos efetuados em seu salário a título de empréstimo consignado.'),
('Restituição de Descontos - Contribuição Sindical', 'Reclamante pede a restituição de descontos efetuados em seu salário a título de contribuição sindical.'),
('Restituição de Descontos - Mensalidade Sindical', 'Reclamante pede a restituição de descontos efetuados em seu salário a título de mensalidade sindical.'),
('Restituição de Descontos - Confederativa', 'Reclamante pede a restituição de descontos efetuados em seu salário a título de contribuição confederativa.'),
('Restituição de Descontos - Assistencial', 'Reclamante pede a restituição de descontos efetuados em seu salário a título de contribuição assistencial.'),
('Restituição de Descontos - Indevidos', 'Reclamante pede a restituição de descontos indevidos efetuados em seu salário.'),
('Multa por descumprimento de Acordo', 'Reclamante pede a aplicação de multa por descumprimento de acordo.'),
('Cumprimento de Cláusula Coletiva', 'Reclamante pede o cumprimento de cláusula coletiva.'),
('Tutela de Urgência', 'Reclamante pede tutela de urgência, sem indicar o motivo.'),
('Tutela de Evidência', 'Reclamante pede tutela de evidência.'),
('Tutela Antecipada', 'Reclamante pede tutela antecipada.'),
('Tutela Inibitória', 'Reclamante pede tutela inibitória.'),
('Justiça Gratuita', 'Reclamante pede a concessão dos benefícios da justiça gratuita.'),
('Inversão do Ônus da Prova', 'Reclamante pede a inversão do ônus da prova.'),
('Produção de Prova Pericial', 'Reclamante requer a produção de prova pericial.'),
('Produção de Prova Testemunhal', 'Reclamante requer a produção de prova testemunhal.'),
('Produção de Prova Documental', 'Reclamante requer a produção de prova documental.'),
('Exibição de Documentos', 'Reclamante requer a exibição de documentos pela parte contrária.'),
('Expedição de Ofícios', 'Reclamante requer a expedição de ofícios a órgãos públicos ou privados.'),
('Determinação de Diligências', 'Reclamante requer a determinação de diligências.'),
('Suspensão do Processo', 'Reclamante requer a suspensão do processo.'),
('Extinção do Processo', 'Reclamante requer a extinção do processo.'),
('Arquivamento do Processo', 'Reclamante requer o arquivamento do processo.'),
('Desistência da Ação', 'Reclamante requer a desistência da ação.'),
('Renúncia ao Direito', 'Reclamante renuncia ao direito sobre o qual se funda a ação.'),
('Reconhecimento da Procedência do Pedido', 'Réu reconhece a procedência do pedido.'),
('Conciliação', 'As partes requerem a conciliação.'),
('Acordo', 'As partes requerem a homologação de acordo.'),
('Mediação', 'As partes requerem a mediação.'),
('Arbitragem', 'As partes requerem a arbitragem.'),
('Recurso Ordinário', 'Reclamante interpõe recurso ordinário.'),
('Recurso de Revista', 'Reclamante interpõe recurso de revista.'),
('Embargos', 'Reclamante interpõe embargos.'),
('Embargos de Declaração', 'Reclamante interpõe embargos de declaração.'),
('Agravo de Instrumento', 'Reclamante interpõe agravo de instrumento.'),
('Agravo Regimental', 'Reclamante interpõe agravo regimental.'),
('Agravo Interno', 'Reclamante interpõe agravo interno.'),
('Recurso Extraordinário', 'Reclamante interpõe recurso extraordinário.'),
('Reclamação Constitucional', 'Reclamante interpõe reclamação constitucional.'),
('Mandado de Segurança', 'Reclamante impetra mandado de segurança.'),
('Habeas Corpus', 'Reclamante impetra habeas corpus.'),
('Habeas Data', 'Reclamante impetra habeas data.'),
('Ação Rescisória', 'Reclamante propõe ação rescisória.'),
('Ação Anulatória', 'Reclamante propõe ação anulatória.'),
('Ação Declaratória', 'Reclamante propõe ação declaratória.'),
('Ação Cautelar', 'Reclamante propõe ação cautelar.'),
('Ação de Cumprimento', 'Reclamante propõe ação de cumprimento.'),
('Ação Civil Pública', 'Reclamante propõe ação civil pública.'),
('Ação Coletiva', 'Reclamante propõe ação coletiva.'),
('Dissídio Coletivo', 'Reclamante propõe dissídio coletivo.'),
('Dissídio Individual', 'Reclamante propõe dissídio individual.'),
('Inquérito Judicial', 'Reclamante propõe inquérito judicial para apuração de falta grave.'),
('Consignação em Pagamento', 'Reclamante propõe consignação em pagamento.'),
('Embargos à Execução', 'Reclamante interpõe embargos à execução.'),
('Embargos de Terceiro', 'Reclamante interpõe embargos de terceiro.'),
('Impugnação à Sentença de Liquidação', 'Reclamante interpõe impugnação à sentença de liquidação.'),
('Impugnação aos Cálculos', 'Reclamante interpõe impugnação aos cálculos.'),
('Exceção de Pré-Executividade', 'Reclamante interpõe exceção de pré-executividade.'),
('Exceção de Incompetência', 'Reclamante interpõe exceção de incompetência.'),
('Exceção de Suspeição', 'Reclamante interpõe exceção de suspeição.'),
('Exceção de Impedimento', 'Reclamante interpõe exceção de impedimento.'),
('Penhora', 'Reclamante requer a penhora de bens.'),
('Bloqueio de Valores', 'Reclamante requer o bloqueio de valores via BACENJUD/SISBAJUD.'),
('Bloqueio de Veículos', 'Reclamante requer o bloqueio de veículos via RENAJUD.'),
('Bloqueio de Imóveis', 'Reclamante requer o bloqueio de imóveis.'),
('Desconsideração da Personalidade Jurídica', 'Reclamante requer a desconsideração da personalidade jurídica.'),
('Inclusão no Polo Passivo', 'Reclamante requer a inclusão de terceiros no polo passivo.'),
('Substituição Processual', 'Reclamante requer a substituição processual.'),
('Sucessão Processual', 'Reclamante requer a sucessão processual.'),
('Habilitação de Crédito', 'Reclamante requer a habilitação de crédito.'),
('Adjudicação', 'Reclamante requer a adjudicação de bens.'),
('Arrematação', 'Reclamante requer a arrematação de bens.'),
('Leilão', 'Reclamante requer a realização de leilão.'),
('Hasta Pública', 'Reclamante requer a realização de hasta pública.'),
('Avaliação de Bens', 'Reclamante requer a avaliação de bens.'),
('Liberação de Valores', 'Reclamante requer a liberação de valores.'),
('Expedição de Alvará', 'Reclamante requer a expedição de alvará.'),
('Expedição de Mandado', 'Reclamante requer a expedição de mandado.'),
('Expedição de Ofício', 'Reclamante requer a expedição de ofício.'),
('Expedição de Carta Precatória', 'Reclamante requer a expedição de carta precatória.'),
('Expedição de Carta Rogatória', 'Reclamante requer a expedição de carta rogatória.'),
('Citação', 'Reclamante requer a citação.'),
('Intimação', 'Reclamante requer a intimação.'),
('Notificação', 'Reclamante requer a notificação.'),
('Audiência Inicial', 'Reclamante requer a designação de audiência inicial.'),
('Audiência de Instrução', 'Reclamante requer a designação de audiência de instrução.'),
('Audiência Una', 'Reclamante requer a designação de audiência una.'),
('Audiência de Conciliação', 'Reclamante requer a designação de audiência de conciliação.'),
('Sustentação Oral', 'Reclamante requer sustentação oral.'),
('Memoriais', 'Reclamante requer a apresentação de memoriais.'),
('Razões Finais', 'Reclamante requer a apresentação de razões finais.'),
('Alegações Finais', 'Reclamante requer a apresentação de alegações finais.'),
('Encerramento da Instrução', 'Reclamante requer o encerramento da instrução.'),
('Sentença', 'Reclamante requer a prolação de sentença.'),
('Acórdão', 'Reclamante requer a prolação de acórdão.'),
('Trânsito em Julgado', 'Reclamante requer o trânsito em julgado.'),
('Cumprimento de Sentença', 'Reclamante requer o cumprimento de sentença.'),
('Execução', 'Reclamante requer a execução.'),
('Liquidação de Sentença', 'Reclamante requer a liquidação de sentença.'),
('Arquivamento', 'Reclamante requer o arquivamento.'),
('Baixa do Processo', 'Reclamante requer a baixa do processo.'),
('Restabelecimento do Tíquete Refeição', 'Reclamante pede o restabelecimento do tíquete refeição.'),
('Restabelecimento do Tíquete Alimentação', 'Reclamante pede o restabelecimento do tíquete alimentação.'),
('Restabelecimento do Vale Cultura', 'Reclamante pede o restabelecimento do vale cultura.'),
('Restabelecimento do Vale Combustível', 'Reclamante pede o restabelecimento do vale combustível.'),
('Restabelecimento do Vale Transporte', 'Reclamante pede o restabelecimento do vale transporte.'),
('Restabelecimento do Plano Odontológico', 'Reclamante pede o restabelecimento do plano odontológico.'),
('Restabelecimento do Seguro de Vida', 'Reclamante pede o restabelecimento do seguro de vida.'),
('Restabelecimento da Previdência Privada', 'Reclamante pede o restabelecimento da previdência privada.'),
('Restabelecimento de Benefícios', 'Reclamante pede o restabelecimento de benefícios.'),
('Manutenção de Benefícios', 'Reclamante pede a manutenção de benefícios após o término do contrato.'),
('Indenização por Perda de Chance', 'Reclamante pede indenização por perda de chance.'),
('Responsabilidade subsidiária', 'Reclamante pede a responsabilidade subsidiária do tomador de serviços.'),
('Responsabilidade solidária', 'Reclamante pede a responsabilidade solidária do tomador de serviços.'),
('Reconhecimento de vínculo empregatício', 'Reclamante alega que a terceirização foi ilícita e pede o reconhecimento de vínculo empregatício'),
('Reconhecimento de vínculo - Menor Aprendiz', 'Reclamante alega que o contrato de aprendizagem foi ilícito e pede o reconhecimento do vínculo de emprego'),
('Reconhecimento de vínculo - Estagiário', 'Reclamante alega que o contrato de estágio foi ilícito e pede o reconhecimento do vínculo de emprego'),
('Enquadramento como bancário', 'Reclamante de outra categoria sindical pede o enquadramento como bancário e os direitos decorrentes.'),
('Diferenças de comissões', 'Reclamante pede diferenças de comissões alegando que o cálculo e o pagamento foram incorretos.'),
('Diferenças de PLR - PEX', 'Reclamante pede a integração das parcelas varíaveis pagas sob a rubrica PLR - PEX'),
('DIFERENÇAS DE PLR PELA INTEGRAÇÃO DA GRATIFICAÇÃO SEMESTRAL', 'Reclamante pede a integração da gratificação semestral na base de cálculo de PLR'),
('Diferenças de SRV e reflexos', 'Reclamante alega o pagamento incorreto da verba, requerendo a apresentação de documentos contábeis da agência para apuração da SRV (normalmente mediante laudo contábil).'),
('Integração da remuneração variável', 'Reclamante pede o reconhecimento da natureza salarial da remuneração variável'),
('Integração de comissões', 'Reclamante pede o reconhecimento da natureza salarial das comissões pagas'),
('Integração de luvas', 'Reclamante pede a integração do valor recebido a título de luvas (bônus de retenção de empregado na empresa quando contratado; cláusula que o obriga a permanecer na empresa por determinado período após a contratação).'),
('Pagamento de bônus integral e reflexos', 'Reclamante pede diferenças de bônus alegando que o pagamento foi incorreto da verba, pois diferente da regra estipulada ou por falta de transparência na apuração.'),
('Participação nos lucros e resultados - PLR', 'Reclamante pede o pagamento de PLR do período de afastamento por acidente de trabalho (não utilizar para reflexos em PLR).'),
('PLR Proporcional', 'Reclamante pede o pagamento de diferenças de PLR proporcionais ao período que trabalhou no ano do término do seu contrato de trabalho, bem como, eventualmente, a projeção do aviso prévio proporcional (não utilizar para reflexos em PLR).'),
('Prêmio', 'Reclamante pede o reconhecimento da natureza salarial dos prêmios, com os respectivos reflexos / integrações.'),
('Programa de Participação nos Resultados - PPR', 'Reclamante pede diferenças de PPR, pois alega que não teve acesso ao demonstrativo de cálculo.'),
('Férias em Dobro', 'Reclamante alega que foi obrigado a vender ou fracionar férias, ou que tirou férias apenas "no papel" (formalmente, mas ficou trabalhando) e pede o pagamento em dobro do período total ou parcialmente não usufruído.'),
('Rescisão indireta', 'Reclamante alega que o empregador não cumpre os deveres contratuais e pede a rescisão do contrato de trabalho por justa causa do empregador (rescisão indireta).'),
('Reversão do pedido de demissão em rescisão indireta', 'Reclamante ingressa com ação de rescisão indireta e o empregador faz o desligamento / término do contrato como se fosse pedido de demissão. Ingressa com nova ação (ou adita a ação de rescisão indireta) e pede que seja revertida a demissão a pedido.'),
('Seguro desemprego', 'Reclamante pede a entrega de guias do seguro desemprego ou o pagamento de indenização substitutiva (por ex.: reversão de justa causa; rescisão indireta).'),
('Verbas rescisórias', 'Reclamante pede o pagamento de verbas rescisórias (por ex.: reversão de justa causa; rescisão indireta).'),
('Indenização por dano moral - Transporte de Valores', 'Reclamante pede indenização por dano moral em razão do transporte de valores'),
('Protesto Interruptivo', 'Reclamante pede a interrupção prescricional'),
('Dedução/Compensação cláusula 5ª ou 11ª CCT', 'A decisão aplica a cláusula 5ª ou 11ª da CCT da dedução/compensação da gratificação de função de forma integral ou modulada'),
('Responsabilidade solidária - grupo econômico', 'Reclamante pede a responsabilidade solidária entre as empresas pertencentes ao grupo Santander'),
('Diferenças salariais - Reflexos de outra ação trabalhista', 'Reclamante pede reflexos de uma ação trabalhista na outra'),
('FGTS', 'Reclamante alega que o Banco não depositou o FGTS durante um período ou recolheu de forma indevida.'),
('PLR Adicional', 'Reclamante pede o pagamento do adicional de PLR a partir de 2013 previsto em CCT (não utilizar para reflexos em PLR).'),
('Indenização por dano moral - quebra de sigilo bancário', 'Reclamante pede a indenização por dano moral em razão da quebra de sigilo bancário'),
('Horas extras além 6ª - Escriturário', 'Reclamante alega que tinha direito à jornada de 6 horas, mas trabalhava mais de seis horas por dia, e pede o pagamento das horas que excederem essa jornada como extras'),
('Horas extras além da 6ª - cargo de confiança', 'Reclamante alega que estava enquadrado como bancário comissionado / cargo de confiança e pede o pagamento das horas que excederem a sexta diária como extras'),
('Horas extras além da 8ª - cargo de confiança', 'Reclamante alega que estava enquadrado como bancário comissionado / cargo de confiança e pede o pagamento das horas que excederem a oitava diária como extras'),
('Horas Extras além 8ª - art. 62 III CLT', 'Reclamante não estava sujeito a controle de jornada (art. 62, III da CLT) e alega que não tinha cargo de confiança'),
('Horas extras além da 8ª - cargo de confiança teletrabalho', 'Reclamante não estava sujeito a controle de jornada (art. 62, III da CLT) e alega que não tinha cargo de confiança')
ON CONFLICT (nome) DO UPDATE SET descricao = COALESCE(EXCLUDED.descricao, public.materias_benner.descricao), updated_at = now();