// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { buscarPjeComunicaNoBrowser } from '@/utils/pjeComunicaClient';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// ========================
// Safety shim: avoid calling Edge Function `buscar-djen` from the browser
// ========================
// Some older UI flows still call `supabase.functions.invoke('buscar-djen')`.
// That function can hit WORKER_LIMIT (546) under load. When invoked from the
// browser, we can run the same search directly via the user's IP.
const originalInvoke = client.functions.invoke.bind(client.functions);
// Expor a função original para uso direto quando necessário (bypass do shim)
(client.functions as any).__originalInvoke = originalInvoke;
(client.functions as any).invoke = async (functionName: string, options?: any) => {
  if (functionName === 'buscar-djen') {
    try {
      const body = options?.body ?? {};
      const tipo = body?.tipo as 'palavra-chave' | 'advogado' | 'processo' | 'parte' | undefined;
      const tipoNormalizado = (tipo === 'parte' ? 'palavra-chave' : (tipo ?? 'palavra-chave')) as any;

      const resp = await buscarPjeComunicaNoBrowser({
        tipo: tipoNormalizado,
        palavraChave: body?.palavraChave,
        oab: body?.oab,
        uf: body?.uf,
        numeroProcesso: body?.numeroProcesso,
        siglaTribunal: body?.siglaTribunal,
        dataInicio: body?.dataInicio,
        dataFim: body?.dataFim,
        page: body?.page,
        pageSize: body?.pageSize,
      });

      // Mirror the Edge Function response shape
      return {
        data: {
          success: true,
          cached: false,
          items: resp.items,
          count: resp.totalElements,
          totalElements: resp.totalElements,
          page: resp.page,
          pageSize: resp.pageSize,
          hasMore: resp.hasMore,
        },
        error: null,
      };
    } catch (e: any) {
      // Keep the same contract as supabase-js invoke: do not throw.
      return {
        data: null,
        error: e instanceof Error ? e : new Error(String(e)),
      };
    }
  }

  return await originalInvoke(functionName as any, options);
};

export const supabase = client;